/* HOGAR — limpieza, menaje de cocina, aseo y mascota.

   Nada de esto tiene calorías ni entra en una receta: es un catálogo aparte del
   de ingredientes, a propósito. Meterlo con la comida obligaría a que cada
   cálculo del menú tuviera que saltarse estas líneas.

   n      = EL PRODUCTO. Aquí vienen nombres genéricos para arrancar; la línea se
            convierte en TU producto el día que le pongas marca y formato
            —«Champú Head & Shoulders Classic 400 ml»— y entonces se le quita
            `pendiente`. Lo que viaja a Amazon es este nombre, así que sin marca
            no es comprable.
   cat    = Limpieza | Menaje | Aseo | Mascota. Qué es.
   cajon  = amazon | super | suscripcion. DÓNDE SE COMPRA.
            «suscripcion» no sale nunca en la lista: llega solo. Si se acaba
            antes de tiempo, un click lo manda a la compra de Amazon esa vez.

   Que algo falte NO se dice aquí: eso es del día, lo marcas tú y vive en tu
   estado, no en el catálogo.
*/
window.DATOS_HOGAR = [

  /* ---------- LIMPIEZA ---------- */
  { id:"detergente_de_lavadora", precios:[{f:"2026-09-26",p:36.48,pu:0.26,u:"lavado",donde:"Amazon"},{f:"2026-09-26",p:4.65,pu:0.194,u:"lavado",donde:"Mercadona"}], ultimaCompra:"2024-10",  n:"Bosque Verde Detergente ropa Blanca y Color floral Sensation en c\u00e1psulas (caja 24)", rev:7, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 4,65 euros la caja de 24 c\u00e1psulas (528 g), 0,194 euros por lavado. Sustituye al Ariel Todo En 1 PODS de AmazonFresh (36,48 euros las 140, 0,26 por c\u00e1psula). Su pareja no quiere detergente l\u00edquido, solo pastillas o c\u00e1psulas, y este lo es. CUENTA: con 4 lavadoras a la semana son 40,30 euros al a\u00f1o frente a 54,08 del Ariel, unos 14 euros menos. CONTRAPARTIDA: la caja son 24 c\u00e1psulas y hay que reponer cada mes y medio; la bolsa de Ariel eran 140 y duraba ocho meses. VARIANTE ELEGIDA el 26-sep-2026: la floral Sensation (la caja rosa). Mismo formato y mismo precio que la normal: 24 c\u00e1psulas, 528 g, 4,65 euros, 0,194 por lavado.", pendiente:false },
  { id:"suavizante", precios:[{f:"2026-09-23",p:4.88,pu:0.063,u:"lavado",donde:"Amazon"},{f:"2026-09-26",p:1.8,pu:0.023,u:"lavado",donde:"Mercadona"}],  n:"Bosque Verde Suavizante Hipoalergénico Colonia concentrado, 80 lavados (1,6 L)", rev:7, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026 con la ficha del súper. Sustituye al Flor Nenuco de Amazon (4,88 € por 1,4 L y 78 dosis = 0,063 € por lavado). El Bosque Verde son 1,80 € por 1,6 L y 80 lavados = 0,023 € por lavado: menos de la mitad, y también hipoalergénico.", pendiente:false },
  { id:"quitamanchas", precios:[{f:"2026-09-26",p:3.25,pu:3.25,u:"kg",donde:"Mercadona"}],  n:"Bosque Verde Oxi Active Activador quitamanchas ropa de color, en polvo (bote 1 kg)", rev:6, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 3,25 euros el bote de 1 kg. Sustituye al Vanish Oxi Action de Amazon, que era una marca que propuse yo el 23-sep sin confirmar. Es el de ropa de COLOR.", pendiente:false },
  { id:"pastillas_de_lavavajillas", precios:[{f:"2026-09-26",p:3.65,pu:0.102,u:"lavado",donde:"Mercadona"}],  n:"Bosque Verde Lavavajillas en gel Todo en 1, 36 lavados (720 ml)", rev:6, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 3,65 € la botella, 0,102 € por lavado. Sustituye al Finish Powerball de 80 pastillas de Amazon. OJO, CAMBIA EL FORMATO: era pastilla y ahora es gel, así que la dosificación es distinta. Al ser «todo en 1» debería llevar ya la función de abrillantador y sal: pendiente de confirmar si siguen haciendo falta el abrillantador y la sal Somat.", pendiente:false },
  { id:"abrillantador_de_lavavajillas", precios:[{f:"2026-09-26",p:1.2,pu:1.6,u:"L",donde:"Mercadona"}],  n:"Bosque Verde Abrillantador lavavajillas l\u00edquido (750 ml)", rev:6, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 1,20 euros los 750 ml (1,60 euros/L). Sustituye al Somat de Amazon. Carlos lo sigue usando aunque el gel sea todo en 1.", pendiente:false },
  { id:"limpiamaquinas_lavavajillas", precios:[{f:"2026-09-26",p:1.55,pu:6.2,u:"L",donde:"Mercadona"}],  n:"Bosque Verde Limpiam\u00e1quinas lavavajillas l\u00edquido (250 ml)", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,55 euros los 250 ml (6,20 euros/L). No estaba en la lista. Es el que limpia la m\u00e1quina por dentro, no la vajilla: se pasa con el lavavajillas vac\u00edo cada uno o dos meses.", pendiente:false },
  { id:"ambientador_lavavajillas", precios:[{f:"2026-09-26",p:1.5,donde:"Mercadona"}],  n:"Bosque Verde Ambientador lavavajillas Lim\u00f3n (2 recambios)", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,50 euros el paquete de 2 recambios. No estaba en la lista.", pendiente:false },
  { id:"sal_de_lavavajillas", oculta:true, n:"Somat Sal Especial Lavavajillas", rev:5, cat:"Limpieza", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", nota:"Solo si no usas pastillas todo en uno", pendiente:false },
  { id:"lavavajillas_a_mano", precios:[{f:"2026-09-23",p:0.92,pu:1.84,u:"L",donde:"Amazon"},{f:"2026-09-26",p:1.1,pu:1.834,u:"L",donde:"Mercadona"}],  n:"Bosque Verde Lavavajillas Ultra concentrado a mano (botella 600 ml)", rev:7, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 1,10 euros los 600 ml (1,83 euros/L). Sustituye al Mical de Amazon (0,92 euros los 500 ml, 1,84 euros/L). CURIOSO: el precio por litro es pr\u00e1cticamente el mismo, as\u00ed que aqu\u00ed no se ahorra dinero; lo que se gana es que entra en la compra del s\u00faper y sale un producto del pedido de Amazon.", pendiente:false },
  { id:"limpia_tuberias", precios:[{f:"2026-09-26",p:6.99,pu:9.99,u:"L",donde:"Amazon"}], ultimaCompra:"2025-05",  n:"WC Net Limpia Tuberías con carbón activo", rev:5, cat:"Limpieza", cajon:"amazon", nota:"Precio de Amazon del 26-sep-2026: 6,99 euros (9,99 euros/L, o sea una botella de 700 ml). \u00daltima compra suya: mayo de 2025. Es una compra puntual, no de cada semana: entre la \u00faltima compra (mayo de 2025) y hoy han pasado 16 meses.", pendiente:false },
  { id:"cesta_wc", precios:[{f:"2026-09-26",p:2.95,pu:29.5,u:"kg",donde:"Mercadona"}],  n:"Bref Power Activ Pino, colgador WC (paquete 2 ud, 100 g)", rev:5, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"PASA A MERCADONA el 26-sep-2026: 2,95 euros el paquete de 2 unidades (29,50 euros/kg). Misma marca Bref que compraba en Amazon, pero en el s\u00faper. Antes era \u00abduo pack\u00bb sin formato concreto.", pendiente:false },
  { id:"limpiador_multiusos", n:"Skip Ultimate Limpieza Profunda, detergente líquido", rev:5, cat:"Limpieza", cajon:"amazon", oculta:true, nota:"RETIRADA el 23-sep-2026. Carlos confirma que el detergente de ropa es el Ariel en cápsulas: el Skip líquido no lo compra. Y el hueco de multiusos lo cubre el Don Limpio Friegasuelos, cuya botella pone MULTIUSOS.", pendiente:false },
  { id:"limpiacristales", precios:[{f:"2026-09-26",p:1.2,pu:1.2,u:"L",donde:"Mercadona"}],  n:"Bosque Verde Limpiacristales y multiusos con pistola (botella 1 L)", rev:6, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 1,20 euros la botella de 1 L con pistola. Sustituye al Cristasol, que era una marca que propuse yo el 23-sep sin confirmar. Es limpiacristales Y multiusos, as\u00ed que tambi\u00e9n sirve para encimeras y espejos. Va con la bayeta de cristales y espejos de microfibra.", pendiente:false },
  { id:"limpiador_de_bano_y_antical", oculta:true, n:"Don Limpio Detergente Líquido de Baño, 1,5 L", rev:6, cat:"Limpieza", cajon:"amazon", nota:"CONFIRMADO por Carlos el 23-sep-2026: Amazon marca que lo compró en mayo de 2026. 3,70 € (2,47 €/l), 4,6 estrellas.", pendiente:false },
  { id:"lejia", precios:[{f:"2026-09-26",p:1.15,pu:0.575,u:"L",donde:"Mercadona"}],  n:"Bosque Verde Lejía Perfumada con detergente limón (botella 2 L)", rev:7, cat:"Limpieza", cajon:"super", tienda:"Mercadona", pendiente:false, nota:"RESUELTA el 26-sep-2026 con la ficha de Mercadona: 1,15 € la botella de 2 L (0,575 €/L). Antes estaba sin marca y sin formato a propósito, porque el 23-sep me inventé que era Bosque Verde sin saberlo. Ahora lo dice él." },
  { id:"friegasuelos", precios:[{f:"2026-09-26",p:2.1,pu:1.4,u:"L",donde:"Mercadona"}],  n:"Bosque Verde Limpiahogar desinfectante sin lej\u00eda (botella 1,5 L)", rev:7, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 2,10 euros la botella de 1,5 L (1,40 euros/L). Carlos decidi\u00f3 que este UNO sustituye a los DOS Don Limpio que compraba en Amazon: el friegasuelos de superficies delicadas y el detergente de ba\u00f1o. Vale para suelo con fregona y para superficies con pa\u00f1o. Lo que este producto NO hace es quitar la cal: si alg\u00fan d\u00eda hace falta, lo suyo es el Limpiador Antical Bosque Verde con pistola, que es otro producto.", pendiente:false },
  { id:"bolsas_de_basura_grandes", precios:[{f:"2026-09-26",p:2.3,pu:0.058,u:"bolsa",donde:"Mercadona"}],  n:"Bosque Verde Bolsas de basura envases 30 L, amarillas (paquete 40 ud)", rev:7, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"Ficha de Mercadona del 26-sep-2026: 2,30 euros el paquete de 40 (0,058 euros la bolsa). Son las AMARILLAS del cubo de envases. Antes se llamaban grandes, pero las dos son de 30 L: lo que las distingue es el uso, no el tama\u00f1o.", pendiente:false },
  { id:"bolsas_de_basura_pequenas", precios:[{f:"2026-09-26",p:2.3,pu:0.077,u:"bolsa",donde:"Mercadona"}],  n:"Bosque Verde Bolsas de basura extra 30 L perfumadas (paquete 30 ud)", rev:7, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"Ficha de Mercadona del 26-sep-2026: 2,30 euros el paquete de 30 (0,077 euros la bolsa). Son las PERFUMADAS del cubo de cocina. Antes se llamaban peque\u00f1as, pero las dos son de 30 L: lo que las distingue es el uso, no el tama\u00f1o. Cuestan lo mismo que las amarillas pero vienen 10 menos.", pendiente:false },
  { id:"bayetas", precios:[{f:"2026-09-26",p:1.2,pu:0.134,u:"bayeta",donde:"Mercadona"}],  n:"Bosque Verde Bayeta suave multiusos (paquete 9 ud)", rev:6, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADA A MERCADONA el 26-sep-2026: 1,20 € el paquete de 9 (0,134 € la bayeta). Sustituye a las Vileda de Amazon, que eran una marca que propuse yo el 23-sep sin confirmar.", pendiente:false },
  { id:"bayeta_cristales", precios:[{f:"2026-09-26",p:0.85,pu:0.85,u:"ud",donde:"Mercadona"}],  n:"Bosque Verde Bayeta cristales y espejos de microfibra", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"Añadida el 26-sep-2026 con la ficha de Mercadona: 0,85 € la unidad. Es la de los cristales y los espejos, distinta de la multiusos amarilla.", pendiente:false },
  { id:"bayeta_polvo", precios:[{f:"2026-09-26",p:0.9,pu:0.9,u:"ud",donde:"Mercadona"}],  n:"Bosque Verde Bayeta polvo de microfibra", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"Añadida el 26-sep-2026 con la ficha de Mercadona: 0,90 € la unidad. Es la del polvo de los muebles, distinta de la multiusos amarilla.", pendiente:false },
  { id:"estropajos", precios:[{f:"2026-09-26",p:0.9,pu:0.3,u:"ud",donde:"Mercadona"}],  n:"Bosque Verde Estropajo suciedad resistente (paquete 3 ud)", rev:6, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 0,90 euros el paquete de 3 (0,30 euros la unidad). Sustituye al Scotch-Brite de Amazon. Es el verde, el fuerte: para lo que se pega. Los otros tres tipos de estropajo van en sus propias fichas.", pendiente:false },
  { id:"estropajo_delicado", precios:[{f:"2026-09-26",p:0.9,pu:0.3,u:"ud",donde:"Mercadona"}],  n:"Bosque Verde Estropajo limpieza delicada (paquete 3 ud)", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 0,90 euros el paquete de 3 (0,30 euros la unidad). El azul, el que no raya: para sart\u00e9n antiadherente, cristal y todo lo que se marca.", pendiente:false },
  { id:"estropajo_bano", precios:[{f:"2026-09-26",p:1.0,pu:0.5,u:"ud",donde:"Mercadona"}],  n:"Bosque Verde Estropajo ba\u00f1o (paquete 2 ud)", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,00 euro el paquete de 2 (0,50 euros la unidad). Con esponja y protegido contra bacterias. Va con el ba\u00f1o y no se mezcla con los de la cocina.", pendiente:false },
  { id:"estropajo_almohadilla", precios:[{f:"2026-09-26",p:0.95,pu:0.475,u:"ud",donde:"Mercadona"}],  n:"Bosque Verde Estropajo almohadilla limpieza delicada (paquete 2 ud)", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 0,95 euros el paquete de 2 (0,475 euros la unidad). No raya: es el de las superficies m\u00e1s delicadas.", pendiente:false },
  { id:"limpia_vitroceramica", precios:[{f:"2026-09-26",p:1.7,pu:3.4,u:"L",donde:"Mercadona"}],  n:"Bosque Verde Limpiador Vitrocer\u00e1micas 3 en 1 (botella 500 ml)", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,70 euros los 500 ml (3,40 euros/L). NO ESTABA EN LA LISTA: Carlos lo ech\u00f3 en falta al repasar Limpieza, as\u00ed que nunca hab\u00eda entrado en una compra. 3 en 1: limpia, da brillo sin rayar y deja capa protectora.", pendiente:false },
  { id:"antimosquitos_liquido", precios:[{f:"2026-09-26",p:1.90,donde:"Mercadona"}], n:"Bosque Verde Insecticida antimosquitos el\u00e9ctrico, recambio l\u00edquido (1 ud)", rev:1, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,90 euros el recambio. Es RECAMBIO: el difusor se compra una vez y esto es lo que se repone. De temporada, de mayo a septiembre.", pendiente:false },
  { id:"antimosquitos_pastillas", precios:[{f:"2026-09-26",p:1.55,pu:0.052,u:"pastilla",donde:"Mercadona"}], n:"Bosque Verde Insecticida antimosquitos el\u00e9ctrico, recambio pastillas (caja 30)", rev:1, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,55 euros la caja de 30 pastillas (0,052 euros la pastilla). Es RECAMBIO, igual que el l\u00edquido: Carlos usa los dos aparatos. De temporada, de mayo a septiembre.", pendiente:false },
  { id:"antical", precios:[{f:"2026-09-26",p:1.70,pu:2.267,u:"L",donde:"Mercadona"}], n:"Bosque Verde Limpiador Antical con pistola (botella 750 ml)", rev:1, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,70 euros los 750 ml (2,27 euros/L). CUBRE EL HUECO que qued\u00f3 al retirar el Don Limpio de ba\u00f1o: es el de la cal de la mampara y los grifos, que ni el limpiahogar ni el gel del v\u00e1ter hacen. Desincrusta y abrillanta.", pendiente:false },
  { id:"quitagrasas", precios:[{f:"2026-09-26",p:1.50,pu:2.00,u:"L",donde:"Mercadona"}], n:"Bosque Verde Quitagrasas perfume Marsella con pistola (botella 750 ml)", rev:1, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,50 euros los 750 ml (2,00 euros/L). No estaba en la lista. Es el de la grasa de la cocina: campana, azulejos y horno. Tiene espuma y spray.", pendiente:false },
  { id:"antipolillas", precios:[{f:"2026-09-26",p:1.80,pu:0.90,u:"ud",donde:"Mercadona"}], n:"Bosque Verde Colgador antipolillas Lavanda (paquete 2 ud)", rev:1, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,80 euros el paquete de 2 (0,90 euros la unidad). No estaba en la lista. Dura 2 meses cada colgador seg\u00fan el envase: el paquete da para cuatro meses de un armario.", pendiente:false },
  { id:"detergente_a_mano", precios:[{f:"2026-09-26",p:1.90,pu:2.924,u:"kg",donde:"Mercadona"}], n:"Bosque Verde Detergente lavado a mano en polvo (caja 650 g)", rev:1, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adido el 26-sep-2026 con la ficha de Mercadona: 1,90 euros la caja de 650 g (2,92 euros/kg). NO ESTABA EN LA LISTA: era uno de los huecos detectados al repasar Limpieza. Es el de lavar a mano en el barre\u00f1o, distinto del de la lavadora.", pendiente:false },
  { id:"guantes_latex", precios:[{f:"2026-09-26",p:0.7,pu:0.35,u:"guante",donde:"Mercadona"}],  n:"Bosque Verde Guantes de l\u00e1tex sensibles, talla mediana (1 par)", rev:2, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"A\u00f1adidos el 26-sep-2026 a petici\u00f3n de Carlos: 0,70 euros el par. Van en la lista COMO OPCI\u00d3N, no como compra habitual: usa los desechables de nitrilo y estos los quiere tener apuntados por si alg\u00fan d\u00eda los a\u00f1ade. Como todo lo de Hogar, no entra en la compra hasta que \u00e9l lo marque.", pendiente:false },
  { id:"guantes_de_fregar", precios:[{f:"2026-09-26",p:2.5,pu:0.084,u:"guante",donde:"Mercadona"}],  n:"Bosque Verde Guantes de nitrilo desechables, talla mediana (caja 30 ud)", rev:6, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 2,50 euros la caja de 30 (0,084 euros el guante). Sustituye a los Vileda de fregar de Amazon. OJO: NO SON LO MISMO. Los Vileda eran guantes de goma reutilizables; estos son desechables de nitrilo, sin polvo y aptos para uso alimentario. Se usan y se tiran.", pendiente:false },
  { id:"ambientador", precios:[{f:"2026-09-26",p:19.80,pu:4.95,u:"mikado",donde:"Amazon"}], suplente:"El mismo mikado suelto en Primaprix",  n:"AMBAR Zen Fortaleza \u00c1mbar & Cedro, ambientador mikado 40 ml (pack 4)", rev:8, cat:"Limpieza", cajon:"amazon", nota:"PASA A AMAZON el 26-sep-2026: pack de 4 mikados por 19,80 euros (4,95 euros la unidad), marca Golominas, con Prime. Antes estaba puesto en Primaprix, que sigue teni\u00e9ndolo suelto, pero Carlos lo compra en Amazon por comodidad. OJO: es Amazon normal, NO AmazonFresh, as\u00ed que llega en un env\u00edo aparte de la compra de alimentaci\u00f3n. El vendedor dice que cada mikado dura hasta 4 semanas; si fuera as\u00ed, el pack da unos cuatro meses y sale a unos 5 euros al mes. PENDIENTE (26-sep-2026): Carlos buscar\u00e1 un mikado de olor parecido en Mercadona; si lo encuentra, este se cambia y sale de Amazon.", pendiente:false, },
  { id:"gel_wc_desinfectante", precios:[{f:"2026-09-26",p:1.15,pu:1.15,u:"L",donde:"Mercadona"}],  n:"Bosque Verde Limpiador WC Aqua en gel antical (botella 1 L)", rev:5, cat:"Limpieza", cajon:"super", tienda:"Mercadona", nota:"CAMBIADO A MERCADONA el 26-sep-2026: 1,15 euros el litro. Sustituye al Sanicentro Gel WC Desinfectante de Amazon. OJO AL MATIZ: el Sanicentro se vend\u00eda como DESINFECTANTE y este se vende como ANTICAL. Como gel de inodoro hacen el mismo papel, pero si alg\u00fan d\u00eda lo que importa es desinfectar, Bosque Verde tiene tambi\u00e9n un gel WC desinfectante.", pendiente:false },
  /* ---------- MENAJE DE COCINA ---------- */
  { id:"papel_de_aluminio", n:"by Amazon Papel de aluminio, 30 m × 30 cm", rev:4, cat:"Menaje", cajon:"amazon", pendiente:false },
  { id:"cinta_adhesiva", n:"Scotch Cinta Adhesiva Transparente, 8 rollos", rev:3, cat:"Menaje", cajon:"amazon", pendiente:false },
  { id:"film_transparente", n:"Albal Film transparente", rev:4, cat:"Menaje", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"papel_de_horno", n:"Albal Papel de horno", rev:4, cat:"Menaje", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"papel_para_freidora_de_aire", n:"by Amazon Papel para freidora de aire", rev:4, cat:"Menaje", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", nota:"Los redondos con agujeros, del tamaño de tu cesta", pendiente:false },
  { id:"papel_de_cocina", n:"Scottex Megarollo Papel de cocina, 3 rollos", rev:4, cat:"Menaje", cajon:"amazon", pendiente:false },
  { id:"bolsas_de_congelacion", n:"Albal Bolsas de congelación", rev:4, cat:"Menaje", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"bolsas_de_cierre_zip", n:"Albal Bolsas con cierre zip", rev:4, cat:"Menaje", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"servilletas_de_papel", n:"Colhogar Servilletas de papel", rev:4, cat:"Menaje", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  /* ---------- ASEO ---------- */
  { id:"gel_de_ducha", n:"Deliplus Gel de Ba\u00f1o \u00c1mbar y Vetiver, botella 750 ml (Mercadona)", rev:5, cat:"Aseo", cajon:"super", pendiente:false, tienda:"Mercadona" },
  { id:"champu", n:"Dove Men +Care Champú Fortificante", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026 SIN base: si usas otra por un motivo concreto, cámbiala. Aquí equivocarse cuesta dinero.", pendiente:false },
  { id:"acondicionador", n:"Dove Men +Care Acondicionador Fortificante", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026 SIN base: si usas otra por un motivo concreto, cámbiala. Aquí equivocarse cuesta dinero.", pendiente:false },
  { id:"desodorante", n:"Dove Men +Care Clean Comfort aerosol 72 h", rev:4, cat:"Aseo", cajon:"amazon", nota:"También compras el Rexona Men Advanced Protection 72 h", pendiente:false },
  { id:"dentifrico", n:"Fluocaril Bi-Fluoré 250 mg pasta dentífrica menta", rev:4, cat:"Aseo", cajon:"amazon", pendiente:false },
  { id:"cepillo_de_dientes", n:"Oral-B Pro-Expert Cepillo Manual, dureza media", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", nota:"Si es eléctrico, aquí van los recambios", pendiente:false },
  { id:"cepillos_interdentales_o_seda_", n:"TePe Cepillos Interdentales, surtido de tallas", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026. El surtido evita acertar la talla a ciegas: pruebas y te quedas con la tuya.", pendiente:false },
  { id:"enjuague_bucal", n:"Fluocaril Colutorio Bi-Fluoré Menta, 2 × 500 ml", rev:4, cat:"Aseo", cajon:"amazon", pendiente:false },
  { id:"cuchillas_de_afeitar", n:"Gillette Mach3 Recambios", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"espuma_o_gel_de_afeitar", n:"Gillette Series Gel de Afeitar, piel sensible", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"crema_hidratante_corporal", n:"Bepanthol Pomada Protectora, 30 g", rev:4, cat:"Aseo", cajon:"amazon", nota:"Para rozaduras y grietas", pendiente:false },
  { id:"salvaslip", n:"Evax Salvaslip Maxi Protegeslip, 40 unidades", rev:3, cat:"Aseo", cajon:"amazon", pendiente:false },
  { id:"tampones", n:"Tampax Pearl Regular con aplicador, 24 unidades", rev:3, cat:"Aseo", cajon:"amazon", pendiente:false },
  { id:"cera_pelo", n:"Got2b Cera fijadora Beach Matt", rev:3, cat:"Aseo", cajon:"amazon", pendiente:false },
  { id:"limpieza_ortodoncia", n:"Corega Ortodoncias y Férulas, 36 tabletas limpiadoras", rev:3, cat:"Aseo", cajon:"amazon", pendiente:false },
  { id:"papel_higienico", n:"Scottex Megarollo Papel Higiénico Seco, 16 rollos", rev:5, cat:"Aseo", cajon:"amazon", nota:"El de 16 rollos equivale a 32 normales", pendiente:false },
  { id:"panuelos_de_papel", n:"Kleenex Original Pañuelos de papel", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"bastoncillos", n:"by Amazon Bastoncillos de algodón", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"jabon_de_manos", n:"Sanex Dermo Protector Jabón de Manos", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026, pendiente de confirmar. Sin formato concreto: el tamaño se elige al pedir.", pendiente:false },
  { id:"protector_solar", n:"ISDIN Fotoprotector Fusion Fluid SPF 50+", rev:4, cat:"Aseo", cajon:"amazon", nota:"Marca propuesta el 23-sep-2026 SIN base: si usas otra por un motivo concreto, cámbiala. Aquí equivocarse cuesta dinero.", nota:"De temporada: para las rutas", pendiente:false },
  /* ---------- MASCOTA ---------- */
  { id:"pienso_del_gato", n:"Pienso del gato", rev:5, cat:"Mascota", cajon:"amazon", oculta:true, nota:"Retirado: el gato solo come lata", pendiente:false },
  { id:"arena_del_gato", n:"Vitakraft Magic Clean Classic, arena no aglomerante, 4,2 kg", rev:4, cat:"Mascota", cajon:"suscripcion", nota:"Suscripción de Amazon: 4 bolsas cada 6 semanas", pendiente:false },
  { id:"comida_humeda_del_gato", n:"Purina Gourmet Gold Mousse, caja 96 × 85 g", rev:4, cat:"Mascota", cajon:"suscripcion", nota:"Suscripción de Amazon: 1 caja cada 6 semanas", pendiente:false },
  { id:"snacks_del_gato", n:"Snacks del gato", rev:4, cat:"Mascota", cajon:"amazon", oculta:true, nota:"Retirado: no los toma", pendiente:false },
  { id:"bolsas_para_recoger_la_arena", n:"Biokat's bolsas XXL de polietileno para la bandeja", rev:4, cat:"Mascota", cajon:"suscripcion", nota:"Suscripción de Amazon: 1 paquete cada 6 semanas", pendiente:false },
  { id:"antiparasitario", n:"Antiparasitario", rev:4, cat:"Mascota", cajon:"amazon", oculta:true, nota:"Retirado: no lo usa", pendiente:false }
];
