/* Catálogo de ingredientes — Asistente de Alimentación (dieta baja en sodio)
   Reorganizado el 23-sep-2026. Tres ejes separados y una sola pregunta por campo:

   cat    = DÓNDE SE COMPRA. Es la sección del supermercado y solo sirve para
            ordenar la lista de la compra. «Restaurante y bar» es lo que NO se
            compra en ningún sitio: nunca entra en la lista.
   racion = LO QUE SUELES TOMAR de una vez. Evita teclear la cantidad cada vez
            que apuntas un plátano o un puñado de pistachos.
   trucos = lo que conviene saber de ese alimento. Vienen de las fichas que
            antes eran recetas de un solo producto.
   sal    = gramos de sal por 100 g / 100 ml.  pesoUd = lo que pesa 1 unidad.
   basico = despensa fija: no entra en la compra semanal salvo que lo marques.

   Que algo sea un capricho NO se dice aquí: depende del día en que te lo comas.
*/
window.DATOS_INGREDIENTES = [


  /* ---------- FRUTAS Y VERDURAS ---------- */
  { id:"ajo", n:"Ajo", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:5, racion:1, sal:0.04, k:140, p:6, g:0.5, h:30, basico:true },
  { id:"albahaca", n:"Albahaca fresca", cat:"Frutas y verduras", u:"g", sal:0.02, k:23, p:3.2, g:0.6, h:2.6 },
  { id:"albaricoque", n:"Albaricoque", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:35, racion:1, sal:0, k:48, p:1.4, g:0.39, h:11.1, compra:"unidades" },
  { id:"arandanos", n:"Arándanos o frambuesas", cat:"Frutas y verduras", u:"g", sal:0, k:57, p:0.7, g:0.3, h:14 },
  { id:"berenjena", n:"Berenjena", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:250, racion:1, sal:0.01, k:25, p:1, g:0.2, h:6 },
  { id:"brotes_verdes", n:"Brotes verdes (bolsa ensalada)", cat:"Frutas y verduras", u:"g", sal:0.05, k:20, p:2, g:0.3, h:2 },
  { id:"calabacin", n:"Calabacín", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:250, racion:1, sal:0.02, k:17, p:1.2, g:0.3, h:3 },
  { id:"cebolla_dulce", n:"Cebolla dulce", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:150, racion:1, sal:0.01, k:40, p:1.1, g:0.1, h:9 },
  { id:"espinacas", n:"Espinacas frescas", cat:"Frutas y verduras", u:"g", sal:0.2, k:23, p:2.9, g:0.4, h:3.6 },
  { id:"fruta_temporada", n:"Fruta de temporada (pera, kiwi, naranja…)", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:150, racion:1, sal:0, k:55, p:0.7, g:0.2, h:13 },
  { id:"limon", n:"Limón", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:110, racion:1, sal:0, k:29, p:1.1, g:0.3, h:9 },
  { id:"mango", n:"Mango", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:350, racion:1, sal:0, k:60, p:0.8, g:0.4, h:15 },
  { id:"manzana_reineta", n:"Manzana reineta o golden", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:180, racion:1, sal:0, k:52, p:0.3, g:0.2, h:14 },
  { id:"melocoton", n:"Melocotón", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:150, racion:1, sal:0, k:39, p:0.91, g:0.25, h:9.5, compra:"unidades" },
  { id:"patata", n:"Patata", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:180, racion:1, sal:0.02, k:77, p:2, g:0.1, h:17 },
  { id:"perejil", n:"Perejil fresco", cat:"Frutas y verduras", u:"g", sal:0.14, k:36, p:3, g:0.8, h:6, basico:true },
  { id:"pina_fresca", n:"Piña fresca", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:1200, racion:1, sal:0, k:50, p:0.5, g:0.1, h:13 },
  { id:"platano", n:"Plátano", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:120, racion:1, sal:0, k:89, p:1.1, g:0.3, h:23 },
  { id:"puerro", n:"Puerro", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:150, racion:1, sal:0.05, k:61, p:1.5, g:0.3, h:14 },
  { id:"setas", n:"Setas o champiñones frescos", cat:"Frutas y verduras", u:"g", sal:0.01, k:22, p:3.1, g:0.3, h:3.3 },
  { id:"tomate", n:"Tomate maduro", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:150, racion:1, sal:0.01, k:18, p:0.9, g:0.2, h:3.9 },
  { id:"zanahoria", n:"Zanahoria", rev:2, cat:"Frutas y verduras", u:"ud", pesoUd:80, racion:1, sal:0.17, k:41, p:0.9, g:0.2, h:10 },

  /* ---------- CARNICERÍA ---------- */
  { id:"ternera_picada", n:"Carne picada magra de ternera", cat:"Carnicería", u:"g", sal:0.15, k:180, p:20, g:11, h:0, compra:"bandeja" },
  { id:"chorizo_sarta_en_tacos", n:"Chorizo sarta en tacos", cat:"Carnicería", u:"g", sal:3.5, k:448, p:24.4, g:38.4, h:1.2, de:"ia" },
  { id:"chorizo_sarta_en_tacos_2", n:"Chorizo sarta en tacos", cat:"Carnicería", u:"g", sal:3.5, k:448, p:24.4, g:38.4, h:1.2, de:"ia" },
  { id:"ternera_entrecot", n:"Entrecot de ternera", cat:"Carnicería", u:"g", sal:0.15, k:220, p:20, g:15, h:0, compra:"pieza" },
  { id:"hamburguesa_bajasal", n:"Hamburguesa de vacuno baja en sal (≤0,25 g/100 g)", rev:2, cat:"Carnicería", u:"ud", pesoUd:150, racion:1, sal:0.25, k:200, p:19, g:14, h:1, compra:"unidades" },
  { id:"cerdo_lomo", n:"Lomo de cerdo fresco en filetes (sin adobar)", cat:"Carnicería", u:"g", sal:0.15, k:145, p:22, g:6, h:0, compra:"bandeja" },
  { id:"pollo_pechuga", n:"Pechuga de pollo fresca", cat:"Carnicería", u:"g", sal:0.15, k:110, p:23, g:1.5, h:0, compra:"bandeja" },
  { id:"cerdo_solomillo", n:"Solomillo de cerdo fresco", cat:"Carnicería", u:"g", sal:0.15, k:120, p:21, g:4, h:0, compra:"pieza" },

  /* ---------- PESCADERÍA ---------- */
  { id:"atun_fresco", n:"Atún fresco (lomo)", cat:"Pescadería", u:"g", sal:0.15, k:145, p:23, g:5, h:0, compra:"pieza" },
  { id:"calamar_fresco", n:"Calamar fresco limpio", cat:"Pescadería", u:"g", sal:0.25, k:80, p:16, g:1.3, h:1.5, compra:"pieza" },
  { id:"bacalao_natural", n:"Lomo de bacalao al natural SIN SALAR (congelado)", rev:2, cat:"Pescadería", u:"ud", pesoUd:130, racion:1, sal:0.16, k:80, p:18, g:0.7, h:0, compra:"paquete", nota:"Nunca desalado ni en salazón" },
  { id:"merluza_lomo", n:"Lomo de merluza fresca o congelada", cat:"Pescadería", u:"g", sal:0.25, k:72, p:17, g:0.8, h:0, compra:"lomos" },
  { id:"salmon_lomo", n:"Lomo de salmón fresco o congelado", cat:"Pescadería", u:"g", sal:0.15, k:200, p:20, g:13, h:0, compra:"lomos" },
  { id:"lubina", n:"Lomos de lubina congelados sin aditivos", rev:2, cat:"Pescadería", u:"g", sal:0.2, k:154, p:21, g:7.5, h:0, compra:"paquete", nota:"La Sirena Premium, paquete de 180 g. Ingrediente único: lubina. Rechaza los que lleven polifosfatos (E-451/E-452), salmuera o sal añadida" },

  /* ---------- CHARCUTERÍA Y QUESOS ---------- */
  { id:"jamon_iberico", n:"Jamón ibérico de bellota, loncheado", rev:2, cat:"Charcutería y quesos", u:"g", racion:30, sal:5.1, k:433, p:32.2, g:33.8, h:0.1, compra:"sobre", nota:"LO MÁS SALADO DE TODO EL CATÁLOGO: 5,1 g de sal por 100 g. 30 g ya son 1,5 g de sal", trucos:["132 kcal y 1,53 g de sal. ES EL PRODUCTO MÁS SALADO DE TODO TU CATÁLOGO: 5,1 g de sal por 100 g.","Un plato de tapa se lleva el 38% de tu tope diario de sal. Dos platos y ya vas por encima del aviso ámbar sin haber comido nada más.","Si lo tomas, el resto del día tiene que ir muy limpio de sal: sin pan Ortiz, sin queso y sin aceitunas."] },
  { id:"queso_curado", n:"Queso curado de oveja (manchego)", rev:2, cat:"Charcutería y quesos", u:"g", racion:45, sal:2.1, k:455, p:27, g:38, h:1.3, compra:"cuña", nota:"Una loncha de 45 g son 0,95 g de sal: como el pan Ortiz de todo el día", trucos:["205 kcal y 0,95 g de sal. Una sola loncha lleva tanta sal como el pan Ortiz de todo el día.","12 g de proteína, eso sí. Pero para proteína tienes el requesón y el queso de Burgos sin sal a 0,02 g."] },
  { id:"salchichas_oscar_mayer_tipo_fr", n:"Salchichas Oscar Mayer tipo Frankfurt", rev:2, cat:"Charcutería y quesos", u:"ud", pesoUd:29, racion:1, sal:2, k:240, p:11, g:20.5, h:2, de:"ia" },

  /* ---------- LÁCTEOS Y HUEVOS ---------- */
  { id:"huevo", n:"Huevos", rev:2, cat:"Lácteos y huevos", u:"ud", pesoUd:55, racion:1, sal:0.35, k:143, p:13, g:9.5, h:0.7 },
  { id:"leche", n:"Leche", cat:"Lácteos y huevos", u:"ml", sal:0.1, k:46, p:3.2, g:1.6, h:4.8 },
  { id:"leche_desnatada", n:"Leche desnatada", rev:1, cat:"Lácteos y huevos", u:"ml", sal:0.13, k:35, p:3.4, g:0.3, h:4.9, basico:true },
  { id:"leche_entera", n:"Leche entera", cat:"Lácteos y huevos", u:"ml", sal:0.12, k:64, p:3.3, g:3.6, h:4.6, compra:"brick" },
  { id:"mozzarella_fresca", n:"Mozzarella fresca de bola", cat:"Lácteos y huevos", u:"g", sal:0.35, k:250, p:18, g:19, h:2 },
  { id:"parmigiano_reggiano_en_cuna_ra", n:"Parmigiano Reggiano en cuña, rallado al momento", rev:2, cat:"Lácteos y huevos", u:"g", sal:1.5, k:397, p:32.4, g:29.7, h:0, de:"ia" },
  { id:"queso_el_caserio_rallado_espec", n:"Queso El Caserío rallado especial pasta", rev:2, cat:"Lácteos y huevos", u:"g", sal:5.53, k:300, p:21, g:21, h:3.7, de:"ia" },
  { id:"queso_burgos_sinsal", n:"Queso fresco tipo Burgos 0% sal añadida", cat:"Lácteos y huevos", u:"g", sal:0.1, k:130, p:12, g:8, h:3 },
  { id:"requeson", n:"Requesón fresco (o ricotta)", cat:"Lácteos y huevos", u:"g", sal:0.12, k:98, p:11, g:4.3, h:3.4 },
  { id:"yogur_griego", n:"Yogur griego natural sin azúcar", rev:2, cat:"Lácteos y huevos", u:"ud", pesoUd:125, racion:1, sal:0.09, k:59, p:10, g:0.4, h:3.6 },
  { id:"yogur_desnatado", n:"Yogur natural desnatado bio", rev:3, cat:"Lácteos y huevos", u:"ud", pesoUd:125, racion:1, sal:0.13, k:42, p:4.3, g:0.2, h:5.7, nota:"Alternativa al griego: 42 kcal menos por tarrina pero 7 g menos de proteína. El recetario usa el griego" },
  { id:"yogur_natural", n:"Yogur natural sin azúcar", rev:2, cat:"Lácteos y huevos", u:"ud", pesoUd:125, racion:1, sal:0.13, k:61, p:3.5, g:3.3, h:4.7 },

  /* ---------- PANADERÍA ---------- */
  { id:"croissant", n:"Croissant de bollería (ración 36 g)", rev:2, cat:"Panadería", u:"ud", pesoUd:36, racion:1, sal:0.61, k:447, p:7.2, g:27, h:43, compra:"paquete", nota:"36 g es la ración que declara la etiqueta. Un croissant de panadería pesa el doble: si es de los grandes, pon 2", trucos:["161 kcal y 0,22 g de sal por la ración de 36 g que declara la etiqueta.","Ojo con el tamaño: un croissant de panadería pesa 60-70 g, casi el doble. Si es de esos, pon 2 en el contador."] },
  { id:"donut_panrico", n:"Donut Panrico glacé (unidad 52 g)", rev:2, cat:"Panadería", u:"ud", pesoUd:52, racion:1, sal:1, k:332, p:5.5, g:17, h:38, compra:"paquete", nota:"0,52 g de sal por donut: dos donuts llevan más sal que el pan Ortiz de todo un día", trucos:["173 kcal y 0,52 g de sal el donut. Dos son 345 kcal y 1,04 g de sal: más sal que las seis rebanadas de pan Ortiz de todo un día (0,91 g).","La sal de la bollería no se nota al paladar porque va tapada por el azúcar. Por eso sorprende cuando la miras."] },
  { id:"magdalena", n:"Magdalena redonda (unidad 29 g)", rev:2, cat:"Panadería", u:"ud", pesoUd:29, racion:1, sal:0.17, k:433, p:4.4, g:22, h:51, compra:"paquete", trucos:["126 kcal y 0,05 g de sal. Es, de lejos, el capricho de bollería con menos sal: diez veces menos que un donut.","Si el capricho es por el dulce y no por el donut en concreto, esta sale mucho más barata en las dos cuentas."] },
  { id:"palmera_choco", n:"Palmera de chocolate (unidad 80 g)", rev:2, cat:"Panadería", u:"ud", pesoUd:80, racion:1, sal:0.7, k:541, p:6, g:37, h:46, compra:"unidades", nota:"Dato orientativo: las palmeras de pastelería van de 80 a 115 g y de 0,6 a 1,6 g de sal por 100 g", trucos:["433 kcal y 0,56 g de sal. Es el capricho más caro en calorías de la lista después del Whopper y la tarta de queso.","El dato es orientativo: las palmeras no llevan etiqueta fija y van de 80 a 115 g según la pastelería."] },
  { id:"pan_sin_sal", n:"Pan artesanal SIN SAL (barra o rebanadas congeladas)", rev:2, cat:"Panadería", u:"ud", pesoUd:40, racion:1, sal:0.05, k:265, p:8.5, g:1.5, h:52, nota:"Encargar en panadería; congelar en rebanadas" },
  { id:"pan_ortiz_bajosal", n:"Pan tostado 100% integral BAJO EN SAL (rebanada 10,8 g)", rev:2, cat:"Panadería", u:"ud", pesoUd:10.8, racion:1, sal:0.2, k:388, p:17.7, g:11, h:47, compra:"paquete", nota:"Hacendado, 0,2 g de sal/100 g. Más proteína que el Recondo, pero siete veces más sal" },
  { id:"pan_tostado_sinsal", n:"Pan tostado INTEGRAL SIN SAL (rebanada 10,8 g)", rev:2, cat:"Panadería", u:"ud", pesoUd:10.8, racion:1, sal:0.03, k:373, p:14, g:4.8, h:64, compra:"paquete", nota:"Recondo integral sin sal ni azúcar añadidos, en Carrefour (270 g, unos 2,55 €). 0,03 g de sal por 100 g: 47 veces menos que el Ortiz" },
  { id:"pan_ortiz", n:"Pan tostado Ortiz estilo tradicional (rebanada 10,8 g)", rev:2, cat:"Panadería", u:"ud", pesoUd:10.8, racion:1, sal:1.4, k:399, p:11, g:6.8, h:70, compra:"paquete", nota:"1,4 g de sal por 100 g: es de lo más salado que entra en la dieta. Mira el apartado del pan en la receta" },
  { id:"pan_panecillo_sinsal", n:"Panecillo sin sal Alipende (unidad 70 g)", rev:2, cat:"Panadería", u:"ud", pesoUd:70, racion:1, sal:0.01, k:317, p:9.76, g:1.34, h:65, compra:"unidades", nota:"Alipende, 4 unidades por 1,68 €. 0,01 g de sal por 100 g: 140 veces menos que el Ortiz. Un panecillo entero lleva 0,007 g de sal" },

  /* ---------- CONGELADOS ---------- */
  { id:"guisantes", n:"Guisantes tiernos (congelados)", cat:"Congelados", u:"g", sal:0.01, k:81, p:5.4, g:0.4, h:14 },
  { id:"helado_choco", n:"Helado de chocolate (tarrina)", rev:2, cat:"Congelados", u:"g", racion:50, sal:0.09, k:202, p:3.3, g:8.3, h:27, compra:"tarrina", trucos:["101 kcal y 0,05 g de sal. Prácticamente lo mismo que el de vainilla."] },
  { id:"helado_vainilla", n:"Helado de vainilla (tarrina)", rev:2, cat:"Congelados", u:"g", racion:50, sal:0.11, k:195, p:2.1, g:7.5, h:29, compra:"tarrina", nota:"La ración de etiqueta son 50 g, que es más o menos una bola", trucos:["98 kcal y 0,06 g de sal. El capricho frío más barato de la lista.","La trampa del helado no es la bola, es la tarrina: 622 g son 1.213 kcal. Sirve en cuenco, no comas del envase."] },
  { id:"do_casa_di_mama_4_formaggi", n:"Pizza Casa di Mama 4 Formaggi (Dr. Oetker, 410 g)", rev:2, cat:"Congelados", u:"g", racion:205, sal:1.2, k:211, p:9.5, g:7.2, h:27, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 433 kcal y 2.46 g de sal", trucos:["433 kcal y 2.46 g de sal la media pizza. Son el 24% de tus calorías del día y el 62% de tu tope de sal.","La pizza entera (410 g) son 865 kcal y 4.92 g de sal: te pasarías del día de sal tú solo.","19 g de proteína en la media pizza, que no está mal.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_casa_di_mama_bbq_pulled_pork", n:"Pizza Casa di Mama BBQ Pulled Pork (Dr. Oetker, 405 g)", rev:2, cat:"Congelados", u:"g", racion:202.5, sal:1.2, k:196, p:9.1, g:4.1, h:29, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 397 kcal y 2.43 g de sal", trucos:["397 kcal y 2.43 g de sal la media pizza. Son el 22% de tus calorías del día y el 61% de tu tope de sal.","La pizza entera (405 g) son 794 kcal y 4.86 g de sal: te pasarías del día de sal tú solo.","18 g de proteína en la media pizza, que no está mal.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_casa_di_mama_bolognese", n:"Pizza Casa di Mama Bolognese (Dr. Oetker, 420 g)", rev:2, cat:"Congelados", u:"g", racion:210, sal:1.2, k:184, p:8.1, g:4.8, h:27, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 386 kcal y 2.52 g de sal", trucos:["386 kcal y 2.52 g de sal la media pizza. Son el 22% de tus calorías del día y el 63% de tu tope de sal.","La pizza entera (420 g) son 773 kcal y 5.04 g de sal: te pasarías del día de sal tú solo.","17 g de proteína en la media pizza, que no está mal.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_casa_di_mama_prosciutto_funghi", n:"Pizza Casa di Mama Prosciutto-Funghi (Dr. Oetker, 405 g)", rev:2, cat:"Congelados", u:"g", racion:202.5, sal:1.2, k:185, p:8.5, g:4.3, h:27, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 375 kcal y 2.43 g de sal", trucos:["375 kcal y 2.43 g de sal la media pizza. Son el 21% de tus calorías del día y el 61% de tu tope de sal.","La pizza entera (405 g) son 749 kcal y 4.86 g de sal: te pasarías del día de sal tú solo.","17 g de proteína en la media pizza, que no está mal.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_casa_di_mama_speciale", n:"Pizza Casa di Mama Speciale (Dr. Oetker, 415 g)", rev:2, cat:"Congelados", u:"g", racion:207.5, sal:1.3, k:202, p:9.1, g:6.4, h:27, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 419 kcal y 2.7 g de sal", trucos:["419 kcal y 2.7 g de sal la media pizza. Son el 24% de tus calorías del día y el 67% de tu tope de sal.","La pizza entera (415 g) son 838 kcal y 5.39 g de sal: te pasarías del día de sal tú solo.","19 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_casa_di_mama_tonno", n:"Pizza Casa di Mama Tonno (Dr. Oetker, 435 g)", rev:2, cat:"Congelados", u:"g", racion:217.5, sal:1.1, k:186, p:9.3, g:5, h:26, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 405 kcal y 2.39 g de sal", trucos:["405 kcal y 2.39 g de sal la media pizza. Son el 23% de tus calorías del día y el 60% de tu tope de sal.","La pizza entera (435 g) son 809 kcal y 4.79 g de sal: te pasarías del día de sal tú solo.","20 g de proteína en la media pizza, que no está mal.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_la_mia_grande_4_formaggi", n:"Pizza La Mia Grande 4 Formaggi (Dr. Oetker, 400 g)", rev:2, cat:"Congelados", u:"g", racion:200, sal:1.3, k:243, p:11, g:11, h:25, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 486 kcal y 2.6 g de sal", trucos:["486 kcal y 2.6 g de sal la media pizza. Son el 27% de tus calorías del día y el 65% de tu tope de sal.","La pizza entera (400 g) son 972 kcal y 5.2 g de sal: te pasarías del día de sal tú solo.","22 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_la_mia_grande_prosciutto_e_formagg", n:"Pizza La Mia Grande Prosciutto e Formaggi (Dr. Oetker, 400 g)", rev:2, cat:"Congelados", u:"g", racion:200, sal:1.3, k:219, p:11, g:8.3, h:25, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 438 kcal y 2.6 g de sal", trucos:["438 kcal y 2.6 g de sal la media pizza. Son el 25% de tus calorías del día y el 65% de tu tope de sal.","La pizza entera (400 g) son 876 kcal y 5.2 g de sal: te pasarías del día de sal tú solo.","22 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_la_mia_grande_rucola", n:"Pizza La Mia Grande Rucola (Dr. Oetker, 410 g)", rev:2, cat:"Congelados", u:"g", racion:205, sal:1.1, k:204, p:10, g:7.1, h:25, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 418 kcal y 2.26 g de sal", trucos:["418 kcal y 2.26 g de sal la media pizza. Son el 23% de tus calorías del día y el 56% de tu tope de sal.","La pizza entera (410 g) son 836 kcal y 4.51 g de sal: te pasarías del día de sal tú solo.","20 g de proteína en la media pizza, que no está mal.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_la_mia_grande_tonno_e_cipolle", n:"Pizza La Mia Grande Tonno e Cipolle (Dr. Oetker, 415 g)", rev:2, cat:"Congelados", u:"g", racion:207.5, sal:1.2, k:212, p:12, g:7.5, h:24, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 440 kcal y 2.49 g de sal", trucos:["440 kcal y 2.49 g de sal la media pizza. Son el 25% de tus calorías del día y el 62% de tu tope de sal.","La pizza entera (415 g) son 880 kcal y 4.98 g de sal: te pasarías del día de sal tú solo.","25 g de proteína en la media pizza, que no está mal.","Ojo con la gama: Casa di Mama y La Mia Grande pesan más que las Ristorante, así que aunque la sal por 100 g sea parecida, la media pizza siempre pasa de 2,2 g.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_al_salame_vegano", n:"Pizza Ristorante al Salame Vegano (Dr. Oetker, 295 g)", rev:2, cat:"Congelados", u:"g", racion:147.5, sal:1.1, k:241, p:4.6, g:11, h:31, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 355 kcal y 1.62 g de sal", trucos:["355 kcal y 1.62 g de sal la media pizza. Son el 20% de tus calorías del día y el 41% de tu tope de sal.","La pizza entera (295 g) son 711 kcal y 3.25 g de sal: te pasarías del día de sal tú solo.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_barbacoa", n:"Pizza Ristorante Barbacoa (Dr. Oetker, 340 g)", rev:2, cat:"Congelados", u:"g", racion:170, sal:1.3, k:236, p:9.5, g:9.6, h:28, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 401 kcal y 2.21 g de sal", trucos:["401 kcal y 2.21 g de sal la media pizza. Son el 23% de tus calorías del día y el 55% de tu tope de sal.","La pizza entera (340 g) son 802 kcal y 4.42 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_bolognese", n:"Pizza Ristorante Bolognese (Dr. Oetker, 375 g)", rev:2, cat:"Congelados", u:"g", racion:187.5, sal:1, k:206, p:8.2, g:9, h:23, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 386 kcal y 1.88 g de sal", trucos:["386 kcal y 1.88 g de sal la media pizza. Son el 22% de tus calorías del día y el 47% de tu tope de sal.","La pizza entera (375 g) son 772 kcal y 3.75 g de sal: te pasarías del día de sal tú solo.","15 g de proteína en la media pizza, que no está mal.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_carbonara", n:"Pizza Ristorante Carbonara (Dr. Oetker, 340 g)", rev:2, cat:"Congelados", u:"g", racion:170, sal:1.3, k:242, p:9.4, g:12, h:24, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 411 kcal y 2.21 g de sal", trucos:["411 kcal y 2.21 g de sal la media pizza. Son el 23% de tus calorías del día y el 55% de tu tope de sal.","La pizza entera (340 g) son 823 kcal y 4.42 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_diavola", n:"Pizza Ristorante Diavola (Dr. Oetker, 350 g)", rev:2, cat:"Congelados", u:"g", racion:175, sal:1.3, k:236, p:8.9, g:12, h:24, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 413 kcal y 2.27 g de sal", trucos:["413 kcal y 2.27 g de sal la media pizza. Son el 23% de tus calorías del día y el 57% de tu tope de sal.","La pizza entera (350 g) son 826 kcal y 4.55 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_funghi", n:"Pizza Ristorante Funghi (Dr. Oetker, 365 g)", rev:2, cat:"Congelados", u:"g", racion:182.5, sal:0.96, k:222, p:7.9, g:11, h:22, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 405 kcal y 1.75 g de sal", trucos:["405 kcal y 1.75 g de sal la media pizza. Son el 23% de tus calorías del día y el 44% de tu tope de sal.","La pizza entera (365 g) son 810 kcal y 3.5 g de sal: te pasarías del día de sal tú solo.","Con 0.96 g de sal por 100 g es de las MENOS saladas del catálogo de Dr. Oetker. Ninguna baja de 0,89.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_hawaii", n:"Pizza Ristorante Hawaii (Dr. Oetker, 355 g)", rev:2, cat:"Congelados", u:"g", racion:177.5, sal:1, k:218, p:8.5, g:8.5, h:26, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 387 kcal y 1.77 g de sal", trucos:["387 kcal y 1.77 g de sal la media pizza. Son el 22% de tus calorías del día y el 44% de tu tope de sal.","La pizza entera (355 g) son 774 kcal y 3.55 g de sal: te pasarías del día de sal tú solo.","15 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_mozzarella", n:"Pizza Ristorante Mozzarella (Dr. Oetker, 355 g)", rev:2, cat:"Congelados", u:"g", racion:177.5, sal:1, k:243, p:10, g:12, h:23, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 431 kcal y 1.77 g de sal", trucos:["431 kcal y 1.77 g de sal la media pizza. Son el 24% de tus calorías del día y el 44% de tu tope de sal.","La pizza entera (355 g) son 863 kcal y 3.55 g de sal: te pasarías del día de sal tú solo.","18 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_mozzarella_sin_gluten", n:"Pizza Ristorante Mozzarella sin gluten (Dr. Oetker, 370 g)", rev:2, cat:"Congelados", u:"g", racion:185, sal:0.93, k:222, p:10, g:10, h:23, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 411 kcal y 1.72 g de sal", trucos:["411 kcal y 1.72 g de sal la media pizza. Son el 23% de tus calorías del día y el 43% de tu tope de sal.","La pizza entera (370 g) son 821 kcal y 3.44 g de sal: te pasarías del día de sal tú solo.","18 g de proteína en la media pizza, que no está mal.","Con 0.93 g de sal por 100 g es de las MENOS saladas del catálogo de Dr. Oetker. Ninguna baja de 0,89.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_pepperoni_salame", n:"Pizza Ristorante Pepperoni-Salame (Dr. Oetker, 320 g)", rev:2, cat:"Congelados", u:"g", racion:160, sal:1.3, k:262, p:10, g:13, h:26, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 419 kcal y 2.08 g de sal", trucos:["419 kcal y 2.08 g de sal la media pizza. Son el 24% de tus calorías del día y el 52% de tu tope de sal.","La pizza entera (320 g) son 838 kcal y 4.16 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_pollo", n:"Pizza Ristorante Pollo (Dr. Oetker, 355 g)", rev:2, cat:"Congelados", u:"g", racion:177.5, sal:1, k:208, p:8.8, g:8.2, h:24, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 369 kcal y 1.77 g de sal", trucos:["369 kcal y 1.77 g de sal la media pizza. Son el 21% de tus calorías del día y el 44% de tu tope de sal.","La pizza entera (355 g) son 738 kcal y 3.55 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_prosciutto", n:"Pizza Ristorante Prosciutto (Dr. Oetker, 340 g)", rev:2, cat:"Congelados", u:"g", racion:170, sal:1.2, k:230, p:9.9, g:10, h:24, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 391 kcal y 2.04 g de sal", trucos:["391 kcal y 2.04 g de sal la media pizza. Son el 22% de tus calorías del día y el 51% de tu tope de sal.","La pizza entera (340 g) son 782 kcal y 4.08 g de sal: te pasarías del día de sal tú solo.","17 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_prosciutto_sin_gluten", n:"Pizza Ristorante Prosciutto sin gluten (Dr. Oetker, 345 g)", rev:2, cat:"Congelados", u:"g", racion:172.5, sal:1.3, k:221, p:11, g:9, h:24, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 381 kcal y 2.24 g de sal", trucos:["381 kcal y 2.24 g de sal la media pizza. Son el 21% de tus calorías del día y el 56% de tu tope de sal.","La pizza entera (345 g) son 762 kcal y 4.49 g de sal: te pasarías del día de sal tú solo.","19 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_quattro_formaggi", n:"Pizza Ristorante Quattro Formaggi (Dr. Oetker, 340 g)", rev:2, cat:"Congelados", u:"g", racion:170, sal:1, k:257, p:11, g:13, h:24, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 437 kcal y 1.7 g de sal", trucos:["437 kcal y 1.7 g de sal la media pizza. Son el 25% de tus calorías del día y el 42% de tu tope de sal.","La pizza entera (340 g) son 874 kcal y 3.4 g de sal: te pasarías del día de sal tú solo.","19 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_rucola", n:"Pizza Ristorante Rucola (Dr. Oetker, 325 g)", rev:2, cat:"Congelados", u:"g", racion:162.5, sal:0.89, k:211, p:8.5, g:8.6, h:25, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 343 kcal y 1.45 g de sal", trucos:["343 kcal y 1.45 g de sal la media pizza. Son el 19% de tus calorías del día y el 36% de tu tope de sal.","La pizza entera (325 g) son 686 kcal y 2.89 g de sal: te pasarías del día de sal tú solo.","Con 0.89 g de sal por 100 g es de las MENOS saladas del catálogo de Dr. Oetker. Ninguna baja de 0,89.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_salame_mozzarella_pesto", n:"Pizza Ristorante Salame Mozzarella Pesto (Dr. Oetker, 360 g)", rev:2, cat:"Congelados", u:"g", racion:180, sal:1.2, k:245, p:9, g:14, h:23, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 441 kcal y 2.16 g de sal", trucos:["441 kcal y 2.16 g de sal la media pizza. Son el 25% de tus calorías del día y el 54% de tu tope de sal.","La pizza entera (360 g) son 882 kcal y 4.32 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_salame_sin_gluten", n:"Pizza Ristorante Salame sin gluten (Dr. Oetker, 315 g)", rev:2, cat:"Congelados", u:"g", racion:157.5, sal:1.4, k:243, p:10, g:11, h:26, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 383 kcal y 2.21 g de sal", trucos:["383 kcal y 2.21 g de sal la media pizza. Son el 22% de tus calorías del día y el 55% de tu tope de sal.","La pizza entera (315 g) son 765 kcal y 4.41 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Con 1.4 g de sal por 100 g es de las MÁS saladas de su catálogo.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_speciale", n:"Pizza Ristorante Speciale (Dr. Oetker, 345 g)", rev:2, cat:"Congelados", u:"g", racion:172.5, sal:1.3, k:235, p:10, g:11, h:24, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 405 kcal y 2.24 g de sal", trucos:["405 kcal y 2.24 g de sal la media pizza. Son el 23% de tus calorías del día y el 56% de tu tope de sal.","La pizza entera (345 g) son 811 kcal y 4.49 g de sal: te pasarías del día de sal tú solo.","17 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_ristorante_spinaci", n:"Pizza Ristorante Spinaci (Dr. Oetker, 390 g)", rev:2, cat:"Congelados", u:"g", racion:195, sal:0.98, k:221, p:7.1, g:11, h:21, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 431 kcal y 1.91 g de sal", trucos:["431 kcal y 1.91 g de sal la media pizza. Son el 24% de tus calorías del día y el 48% de tu tope de sal.","La pizza entera (390 g) son 862 kcal y 3.82 g de sal: te pasarías del día de sal tú solo.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_tonno", n:"Pizza Ristorante Tonno (Dr. Oetker, 355 g)", rev:2, cat:"Congelados", u:"g", racion:177.5, sal:0.94, k:232, p:10, g:10, h:23, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 412 kcal y 1.67 g de sal", trucos:["412 kcal y 1.67 g de sal la media pizza. Son el 23% de tus calorías del día y el 42% de tu tope de sal.","La pizza entera (355 g) son 824 kcal y 3.34 g de sal: te pasarías del día de sal tú solo.","18 g de proteína en la media pizza, que no está mal.","Con 0.94 g de sal por 100 g es de las MENOS saladas del catálogo de Dr. Oetker. Ninguna baja de 0,89.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_ristorante_vegetale", n:"Pizza Ristorante Vegetale (Dr. Oetker, 385 g)", rev:2, cat:"Congelados", u:"g", racion:192.5, sal:0.97, k:186, p:6.7, g:7.9, h:22, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 358 kcal y 1.87 g de sal", trucos:["358 kcal y 1.87 g de sal la media pizza. Son el 20% de tus calorías del día y el 47% de tu tope de sal.","La pizza entera (385 g) son 716 kcal y 3.73 g de sal: te pasarías del día de sal tú solo.","Con 0.97 g de sal por 100 g es de las MENOS saladas del catálogo de Dr. Oetker. Ninguna baja de 0,89.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_rustica_cheese_deluxe", n:"Pizza Rustica Cheese Deluxe (Dr. Oetker, 277.5 g)", rev:2, cat:"Congelados", u:"g", racion:138.75, sal:0.97, k:261, p:12, g:11, h:28, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Rustica viene en pack de 2: 277.5 g es UNA pizza. Media pizza: 362 kcal y 1.35 g de sal", trucos:["362 kcal y 1.35 g de sal la media pizza. Son el 20% de tus calorías del día y el 34% de tu tope de sal.","La pizza entera (277.5 g) son 724 kcal y 2.69 g de sal: te pasarías del día de sal tú solo.","17 g de proteína en la media pizza, que no está mal.","Con 0.97 g de sal por 100 g es de las MENOS saladas del catálogo de Dr. Oetker. Ninguna baja de 0,89.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_rustica_double_pepperoni_cheddar_y", n:"Pizza Rustica Double Pepperoni Cheddar y Mozzarella (Dr. Oetker, 282.5 g)", rev:2, cat:"Congelados", u:"g", racion:141.25, sal:1.3, k:273, p:11, g:12, h:28, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Rustica viene en pack de 2: 282.5 g es UNA pizza. Media pizza: 386 kcal y 1.84 g de sal", trucos:["386 kcal y 1.84 g de sal la media pizza. Son el 22% de tus calorías del día y el 46% de tu tope de sal.","La pizza entera (282.5 g) son 771 kcal y 3.67 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_rustica_ham_cheese", n:"Pizza Rustica Ham & Cheese (Dr. Oetker, 272.5 g)", rev:2, cat:"Congelados", u:"g", racion:136.25, sal:1.1, k:265, p:12, g:11, h:29, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Rustica viene en pack de 2: 272.5 g es UNA pizza. Media pizza: 361 kcal y 1.5 g de sal", trucos:["361 kcal y 1.5 g de sal la media pizza. Son el 20% de tus calorías del día y el 37% de tu tope de sal.","La pizza entera (272.5 g) son 722 kcal y 3 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_rustica_royale", n:"Pizza Rustica Royale (Dr. Oetker, 287.5 g)", rev:2, cat:"Congelados", u:"g", racion:143.75, sal:1, k:217, p:12, g:6.7, h:26, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Rustica viene en pack de 2: 287.5 g es UNA pizza. Media pizza: 312 kcal y 1.44 g de sal", trucos:["312 kcal y 1.44 g de sal la media pizza. Son el 18% de tus calorías del día y el 36% de tu tope de sal.","La pizza entera (287.5 g) son 624 kcal y 2.88 g de sal: te pasarías del día de sal tú solo.","17 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_tradizionale_diavola_calabrese", n:"Pizza Tradizionale Diavola Calabrese (Dr. Oetker, 360 g)", rev:2, cat:"Congelados", u:"g", racion:180, sal:1.3, k:230, p:8.9, g:7.8, h:31, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 414 kcal y 2.34 g de sal", trucos:["414 kcal y 2.34 g de sal la media pizza. Son el 23% de tus calorías del día y el 58% de tu tope de sal.","La pizza entera (360 g) son 828 kcal y 4.68 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Con 1.3 g de sal por 100 g es de las MÁS saladas de su catálogo.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_tradizionale_mozzarella_e_pesto", n:"Pizza Tradizionale Mozzarella e Pesto (Dr. Oetker, 385 g)", rev:2, cat:"Congelados", u:"g", racion:192.5, sal:0.94, k:236, p:8.6, g:9.1, h:30, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 454 kcal y 1.81 g de sal", trucos:["454 kcal y 1.81 g de sal la media pizza. Son el 26% de tus calorías del día y el 45% de tu tope de sal.","La pizza entera (385 g) son 909 kcal y 3.62 g de sal: te pasarías del día de sal tú solo.","17 g de proteína en la media pizza, que no está mal.","Con 0.94 g de sal por 100 g es de las MENOS saladas del catálogo de Dr. Oetker. Ninguna baja de 0,89.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_tradizionale_pancetta_delicata", n:"Pizza Tradizionale Pancetta Delicata (Dr. Oetker, 390 g)", rev:2, cat:"Congelados", u:"g", racion:195, sal:1.1, k:238, p:9.5, g:9.3, h:29, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 464 kcal y 2.15 g de sal", trucos:["464 kcal y 2.15 g de sal la media pizza. Son el 26% de tus calorías del día y el 54% de tu tope de sal.","La pizza entera (390 g) son 928 kcal y 4.29 g de sal: te pasarías del día de sal tú solo.","19 g de proteína en la media pizza, que no está mal.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_tradizionale_quattro_formaggi", n:"Pizza Tradizionale Quattro Formaggi (Dr. Oetker, 380 g)", rev:2, cat:"Congelados", u:"g", racion:190, sal:1, k:244, p:9.8, g:9.2, h:30, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Media pizza: 464 kcal y 1.9 g de sal", trucos:["464 kcal y 1.9 g de sal la media pizza. Son el 26% de tus calorías del día y el 48% de tu tope de sal.","La pizza entera (380 g) son 927 kcal y 3.8 g de sal: te pasarías del día de sal tú solo.","19 g de proteína en la media pizza, que no está mal.","Todo de la etiqueta española oficial de Dr. Oetker."] },
  { id:"do_tradizionale_speciale", n:"Pizza Tradizionale Speciale (Dr. Oetker, 400 g)", rev:2, cat:"Congelados", u:"g", racion:200, sal:1.2, k:222, p:9.7, g:7.9, h:28, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 444 kcal y 2.4 g de sal", trucos:["444 kcal y 2.4 g de sal la media pizza. Son el 25% de tus calorías del día y el 60% de tu tope de sal.","La pizza entera (400 g) son 888 kcal y 4.8 g de sal: te pasarías del día de sal tú solo.","19 g de proteína en la media pizza, que no está mal.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },
  { id:"do_tradizionale_spinaci_e_ricotta", n:"Pizza Tradizionale Spinaci e Ricotta (Dr. Oetker, 415 g)", rev:2, cat:"Congelados", u:"g", racion:207.5, sal:0.97, k:204, p:7.8, g:6.8, h:28, compra:"congelador", nota:"Etiqueta española de Dr. Oetker. Las kcal no las publica la web: están calculadas con la fórmula oficial a partir de sus propios macros. Media pizza: 423 kcal y 2.01 g de sal", trucos:["423 kcal y 2.01 g de sal la media pizza. Son el 24% de tus calorías del día y el 50% de tu tope de sal.","La pizza entera (415 g) son 847 kcal y 4.03 g de sal: te pasarías del día de sal tú solo.","16 g de proteína en la media pizza, que no está mal.","Con 0.97 g de sal por 100 g es de las MENOS saladas del catálogo de Dr. Oetker. Ninguna baja de 0,89.","Peso, macros y sal son de la etiqueta española. Las CALORÍAS están calculadas a partir de esos macros, porque la web de Dr. Oetker no las publica: el método acierta con menos de 3 kcal en las pizzas que sí las traen."] },

  /* ---------- DESPENSA ---------- */
  { id:"aove", n:"Aceite de oliva virgen extra", cat:"Despensa", u:"ml", sal:0, k:900, p:0, g:100, h:0, basico:true },
  { id:"aceite_sesamo", n:"Aceite de sésamo", cat:"Despensa", u:"ml", sal:0, k:900, p:0, g:100, h:0, basico:true },
  { id:"arroz_redondo", n:"Arroz redondo o bomba", cat:"Despensa", u:"g", sal:0.01, k:360, p:7, g:0.6, h:79, basico:true },
  { id:"cacao_puro", n:"Cacao puro 100% desgrasado", cat:"Despensa", u:"g", sal:0.05, k:230, p:20, g:11, h:15, basico:true },
  { id:"cafe_desca", n:"Café descafeinado", cat:"Despensa", u:"g", sal:0, k:0, p:0, g:0, h:0, basico:true },
  { id:"copos_avena", n:"Copos de avena integrales", cat:"Despensa", u:"g", sal:0.02, k:380, p:13, g:7, h:60, basico:true },
  { id:"datiles", n:"Dátiles sin hueso", rev:1, cat:"Despensa", u:"g", sal:0, k:277, p:1.8, g:0.2, h:66, nota:"Los Medjool van mejor para amasar; los secos de bolsa valen y son más baratos" },
  { id:"ketchup", n:"Ketchup", cat:"Despensa", u:"g", sal:1.8, k:102, p:1.2, g:0.2, h:23, de:"ia" },
  { id:"lentejas", n:"Lentejas pardinas", cat:"Despensa", u:"g", sal:0.02, k:340, p:24, g:1.1, h:60, basico:true },
  { id:"mahonesa", n:"Mahonesa", cat:"Despensa", u:"g", sal:1.2, k:680, p:1.1, g:75, h:1.5, de:"ia" },
  { id:"miel", n:"Miel pura", cat:"Despensa", u:"g", sal:0, k:304, p:0.3, g:0, h:82, basico:true },
  { id:"mostaza_bajasal", n:"Mostaza a la antigua baja en sal (o semillas de mostaza)", cat:"Despensa", u:"g", sal:1, k:66, p:4, g:4, h:5, basico:true },
  { id:"zumo_granini", n:"Néctar de naranja Granini (brick 200 ml)", rev:2, cat:"Despensa", u:"ml", racion:200, sal:0, k:41, p:0.5, g:0.1, h:9.4, compra:"pack", nota:"Es NÉCTAR, no zumo exprimido: de concentrado, 50% fruta y con azúcar añadido. El brick de 200 ml son 82 kcal y 18,4 g de azúcar. El fabricante no publica proteína ni grasa", trucos:["82 kcal y 18,4 g de azúcar el brick. Cero sal: por tu oído no hay ningún problema.","No es zumo exprimido: es NÉCTAR, de concentrado, con un 50% de fruta y azúcar añadido. La etiqueta lo dice en pequeño.","18,4 g de azúcar son casi los mismos que una lata de refresco con azúcar. Si el objetivo es bajar peso, este es de los que engañan."] },
  { id:"orejones", n:"Orejones de albaricoque", rev:1, cat:"Despensa", u:"g", sal:0.03, k:241, p:3.4, g:0.5, h:53 },
  { id:"pasas", n:"Pasas sultanas", rev:1, cat:"Despensa", u:"g", sal:0.03, k:299, p:3.1, g:0.5, h:71 },
  { id:"pasta", n:"Pasta (macarrones, hélices, espaguetis)", cat:"Despensa", u:"g", sal:0.01, k:355, p:12, g:1.5, h:72, basico:true },
  { id:"evowhey", n:"Proteína EvoWhey 2.0 de HSN (dosis 30 g)", cat:"Despensa", u:"g", sal:0.79, k:350, p:78, g:3.3, h:6, compra:"bote", nota:"Se compra en hsnstore, no en el súper. Una dosis de 30 g son 23 g de proteína y 105 kcal" },
  { id:"sal", n:"Sal fina", rev:1, cat:"Despensa", u:"g", sal:100, k:0, p:0, g:0, h:0, basico:true, nota:"En todo el recetario solo aparece aquí: en la bebida de reposición de los días de ruta" },
  { id:"chia", n:"Semillas de chía", cat:"Despensa", u:"g", sal:0.04, k:486, p:17, g:31, h:42, basico:true },
  { id:"vinagre", n:"Vinagre de manzana o balsámico", cat:"Despensa", u:"ml", sal:0.02, k:20, p:0, g:0, h:0.5, basico:true },
  { id:"vino_blanco", n:"Vino blanco para cocinar", cat:"Despensa", u:"ml", sal:0.02, k:80, p:0, g:0, h:2.5, basico:true },

  /* ---------- APERITIVOS Y FRUTOS SECOS ---------- */
  { id:"aceitunas_rell", n:"Aceitunas verdes rellenas de anchoa (unidad 4 g)", rev:2, cat:"Aperitivos y frutos secos", u:"ud", pesoUd:4, racion:5, sal:2.6, k:156, p:1.5, g:15.5, h:0.1, compra:"lata", nota:"2,6 g de sal por 100 g. Cinco aceitunas son 0,5 g: la mitad de tu aviso ámbar en cinco bocados", trucos:["Solo 31 kcal, pero 0,50 g de sal: la mitad de tu aviso ámbar en cinco bocados.","Es el caso más engañoso del catálogo. No engordan nada y son de lo más salado que vas a comer en el día.","Las verdes sin rellenar en salmuera son PEORES: 4 g de sal por 100 g frente a 2,6."] },
  { id:"almendras", n:"Almendras crudas sin sal", rev:2, cat:"Aperitivos y frutos secos", u:"g", sal:0.01, k:579, p:21, g:50, h:9 },
  { id:"cacahuetes_sal", n:"Cacahuetes fritos con sal", rev:2, cat:"Aperitivos y frutos secos", u:"g", racion:20, sal:0.82, k:600, p:23, g:48.1, h:14, compra:"bolsa", trucos:["120 kcal y 0,16 g de sal. La menos salada de las cosas de picar.","4,6 g de proteína en el puñado. Si el capricho es salado, este es el que menos daño hace en las dos cuentas."] },
  { id:"crema_cacahuete", n:"Crema de cacahuete 100% sin sal ni azúcar", rev:2, cat:"Aperitivos y frutos secos", u:"g", sal:0.02, k:588, p:25, g:50, h:16, nota:"Mira la etiqueta: la corriente lleva de 0,5 a 1,2 g de sal por 100 g. La buena solo pone «cacahuete 100%»" },
  { id:"mango_deshidratado", n:"Mango deshidratado", rev:2, cat:"Aperitivos y frutos secos", u:"g", racion:30, sal:0.23, k:317, p:2.5, g:1.2, h:70, compra:"bolsa", nota:"Hacendado, sin azúcar añadido. 62 g de azúcar por 100 g: es fruta concentrada, no un snack ligero", trucos:["95 kcal y 0,07 g de sal. Sin azúcar añadido, pero 19 g de azúcar propio del mango en el puñado: al secarlo se concentra.","Para comparar: un mango fresco entero tiene los mismos azúcares repartidos en 200 g de fruta con agua. Deshidratado se come mucho más rápido.","De sal no tiene ningún problema. El aviso es solo por el azúcar."] },
  { id:"doritos", n:"Nachos de maíz tipo Doritos", rev:2, cat:"Aperitivos y frutos secos", u:"g", racion:30, sal:0.97, k:497, p:6.6, g:25.8, h:56.9, compra:"bolsa", trucos:["149 kcal y 0,29 g de sal. Casi lo mismo que las patatas de bolsa."] },
  { id:"nueces", n:"Nueces crudas sin sal", rev:2, cat:"Aperitivos y frutos secos", u:"g", sal:0.01, k:654, p:15, g:65, h:14 },
  { id:"patatas_fritas_congeladas_para", n:"Patatas fritas congeladas para horno o freidora", rev:2, cat:"Aperitivos y frutos secos", u:"g", sal:0.2, k:150, p:2.5, g:5, h:23, de:"ia" },
  { id:"patatas_bolsa", n:"Patatas fritas de bolsa, al punto de sal", rev:2, cat:"Aperitivos y frutos secos", u:"g", racion:30, sal:0.85, k:521, p:6.1, g:31, h:53, compra:"bolsa", nota:"Un puñado son 30 g: 0,25 g de sal. Menos que cinco aceitunas, aunque no lo parezca", trucos:["156 kcal y 0,25 g de sal el puñado. Sorpresa: es MENOS sal que cinco aceitunas (0,50 g) y mucha menos que una loncha de jamón ibérico (1,53 g).","El problema de las patatas no es la sal, es que nadie come 30 g. La bolsa entera de 170 g son 886 kcal y 1,45 g de sal.","Sácalas a un cuenco y guarda la bolsa. Es el único truco que funciona de verdad."] },
  { id:"mcd_patatas_med", n:"Patatas fritas medianas de McDonald's (una ración)", rev:2, cat:"Aperitivos y frutos secos", u:"ud", pesoUd:100, racion:1, sal:0.66, k:320, p:5, g:15, h:43, compra:"restaurante", nota:"Dato de McDonald's EE. UU.: 260 mg de sodio = 0,66 g de sal. Bastante menos saladas de lo que parecen", trucos:["320 kcal y 0,66 g de sal. Sorprende poco saladas para lo que saben: menos de la mitad que el wrap que las acompaña.","Las de Burger King medianas son 386 kcal y 0,7 g: prácticamente iguales."] },
  { id:"pistachos_sal", n:"Pistachos tostados con sal (grano, sin cáscara)", rev:2, cat:"Aperitivos y frutos secos", u:"g", racion:30, sal:0.79, k:617, p:25, g:51, h:10, compra:"bolsa", nota:"Hacendado. El valor es del GRANO pelado: 100 g con cáscara son unos 53 g de grano. La sal varía muchísimo de marca a marca (de 0,7 a 3,2 g/100 g): mira la bolsa", trucos:["185 kcal y 0,24 g de sal el puñado. 7,5 g de proteína, que para un snack está muy bien.","Los mismos 30 g de los 0% sal son 185 kcal y CERO sal. Mismo sabor a pistacho, mismo precio aproximado: es el cambio más barato que puedes hacer.","OJO con la marca: la sal de los pistachos salados va de 0,7 a 3,2 g por 100 g según el fabricante. Con los peores, el puñado se te va a 1 g de sal.","100 g con cáscara son unos 53 g de grano. Si compras con cáscara, cuenta casi la mitad."] },
  { id:"pistachos_sinsal", n:"Pistachos tostados SIN sal (grano, sin cáscara)", rev:2, cat:"Aperitivos y frutos secos", u:"g", sal:0, k:616, p:21.6, g:52.5, h:11, compra:"bolsa", nota:"Hacendado 0% sal. Mismas calorías que los salados y cero sal: para ti es el cambio más barato que hay" },

  /* ---------- DULCES ---------- */
  { id:"chocolate_leche", n:"Chocolate con leche en tableta", rev:2, cat:"Dulces", u:"g", racion:17, sal:0.28, k:539, p:6.5, g:31, h:57, compra:"tableta", nota:"La porción oficial son 4 piezas = 16,7 g", trucos:["90 kcal y 0,05 g de sal. Casi todo lo que aporta es azúcar: 9 g en cuatro onzas.","Una tableta entera de 100 g son 539 kcal. La diferencia entre cuatro onzas y media tableta es de las que se hacen sin pensar."] },
  { id:"chocolate_negro", n:"Chocolate negro 70% cacao", rev:2, cat:"Dulces", u:"g", racion:17, sal:0.1, k:531, p:11, g:36, h:34, compra:"tableta", nota:"La mitad de azúcar que el de leche y casi tres veces menos sal", trucos:["90 kcal, las mismas que el de leche, pero la mitad de azúcar (5 g en vez de 9) y casi tres veces menos sal.","A igualdad de calorías, cambiar de leche a negro 70% es gratis y te quita azúcar. Si el capricho es el chocolate en sí, este gana."] },
  { id:"flan_huevo", n:"Flan de huevo (unidad 110 g)", rev:2, cat:"Dulces", u:"ud", pesoUd:110, racion:1, sal:0.2, k:153, p:4.9, g:4.1, h:24, compra:"pack", trucos:["168 kcal y 0,22 g de sal, con 5,4 g de proteína. 25 g de azúcar, que es lo que tiene de capricho."] },
  { id:"natillas", n:"Natillas de vainilla (unidad 120 g)", rev:2, cat:"Dulces", u:"ud", pesoUd:120, racion:1, sal:0.13, k:109, p:3.1, g:2.9, h:17.7, compra:"pack", nota:"El capricho más barato en calorías de la lista: 131 kcal", trucos:["131 kcal y 0,16 g de sal. Es el capricho más barato en calorías de todos los de esta lista.","Para comparar: tu yogur griego con avena de postre ronda esas mismas calorías, así que cambiar uno por otro un día no mueve la cuenta."] },
  { id:"tarta_queso", n:"Tarta de queso", rev:2, cat:"Dulces", u:"g", racion:90, sal:0.4, k:227, p:8.3, g:12, h:21.3, compra:"tarrina", trucos:["204 kcal y 0,36 g de sal la media tarrina. Entera, 409 kcal y 0,72 g.","7,5 g de proteína en media tarrina: de los postres dulces, el que más lleva."] },

  /* ---------- BEBIDAS ---------- */
  { id:"cerveza", n:"Cerveza rubia (lager, 5,5% vol)", rev:2, cat:"Bebidas", u:"ml", racion:330, sal:0, k:47, p:0, g:0, h:3.5, compra:"pack", nota:"Estrella Galicia Especial. La sal es cero: el precio de la cerveza son las calorías del alcohol, no el sodio. Un tercio son 155 kcal", trucos:["155 kcal y CERO sal. Por tu oído la cerveza no es un problema: no lleva sodio apreciable.","El precio son las calorías, y casi todas vienen del alcohol: 14 g de alcohol por tercio, que son unas 100 de esas 155 kcal.","Tres tercios en una comida con amigos son 465 kcal, un cuarto de tu día, sin haber comido nada.","La 0,0 son 69 kcal el tercio: menos de la mitad, y tampoco tiene sal."] },
  { id:"cerveza_sin", n:"Cerveza SIN alcohol (0,0)", rev:2, cat:"Bebidas", u:"ml", racion:330, sal:0, k:21, p:0, g:0, h:4.7, compra:"pack", nota:"Estrella Galicia 0,0. Menos de la mitad de calorías que la normal y cero sal", trucos:["69 kcal y cero sal. Menos de la mitad que la normal (155). Si la comida con amigos va larga, es la que deja el día entero libre."] },
  { id:"cocacola_zero", n:"Coca-Cola Zero", rev:2, cat:"Bebidas", u:"ml", racion:400, sal:0.01, k:0, p:0, g:0, h:0, compra:"pack", nota:"Cero calorías y prácticamente cero sal: el único capricho que no cuenta en ninguna de las dos cuentas", trucos:["0 kcal y 0,04 g de sal. Es el único capricho de la lista que no mueve ninguna de las dos cuentas.","Si el menú lleva refresco, que sea este: la versión con azúcar son unas 170 kcal en el mismo vaso."] },
  { id:"fanta_lim_zero", n:"Fanta Limón Zero", rev:2, cat:"Bebidas", u:"ml", racion:330, sal:0.06, k:2, p:0, g:0, h:0, compra:"pack", nota:"Tres veces más sal que la Coca-Cola Zero: una lata son 0,20 g. Poco, pero no son intercambiables", trucos:["7 kcal y 0,20 g de sal. Es poco, pero es TRES VECES la sal de la Coca-Cola Zero o la Fanta de naranja.","No son intercambiables: si bebes varias al día, la de limón suma y las otras no."] },
  { id:"fanta_nar_zero", n:"Fanta Naranja Zero", rev:2, cat:"Bebidas", u:"ml", racion:330, sal:0.02, k:3, p:0, g:0, h:0.6, compra:"pack", trucos:["10 kcal y 0,07 g de sal. Prácticamente no cuenta en ninguna de las dos cuentas."] },

  /* ---------- ESPECIAS Y AROMÁTICOS ---------- */
  { id:"ajo_polvo", n:"Ajo en polvo", cat:"Especias y aromáticos", u:"g", sal:0.06, k:331, p:17, g:0.7, h:73, basico:true },
  { id:"canela", n:"Canela en polvo", cat:"Especias y aromáticos", u:"g", sal:0.02, k:247, p:4, g:1.2, h:81, basico:true },
  { id:"comino", n:"Comino molido", cat:"Especias y aromáticos", u:"g", sal:0.04, k:375, p:18, g:22, h:44, basico:true },
  { id:"eneldo", n:"Eneldo seco", cat:"Especias y aromáticos", u:"g", sal:0.05, k:305, p:20, g:4, h:55, basico:true },
  { id:"jengibre", n:"Jengibre fresco o molido", cat:"Especias y aromáticos", u:"g", sal:0.03, k:80, p:1.8, g:0.8, h:18, basico:true },
  { id:"laurel", n:"Laurel", cat:"Especias y aromáticos", u:"g", sal:0.06, k:313, p:8, g:8, h:75, basico:true },
  { id:"oregano", n:"Orégano seco", cat:"Especias y aromáticos", u:"g", sal:0.03, k:265, p:9, g:4, h:69, basico:true },
  { id:"pimenton", n:"Pimentón de la Vera (dulce o ahumado)", cat:"Especias y aromáticos", u:"g", sal:0.1, k:280, p:14, g:13, h:34, basico:true },
  { id:"pimienta", n:"Pimienta negra en molinillo", cat:"Especias y aromáticos", u:"g", sal:0.02, k:250, p:10, g:3, h:64, basico:true },
  { id:"romero", n:"Romero seco", cat:"Especias y aromáticos", u:"g", sal:0.013, k:331, p:5, g:15, h:64, basico:true },
  { id:"tomillo", n:"Tomillo seco", cat:"Especias y aromáticos", u:"g", sal:0.014, k:276, p:9, g:7, h:64, basico:true },

  /* ---------- RESTAURANTE Y BAR ---------- */
  { id:"bk_alita", n:"Alita de pollo de Burger King (unidad 39 g)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:39, racion:1, sal:2, k:203, p:21.2, g:12.8, h:1.2, compra:"restaurante", nota:"Dato OFICIAL de Burger King España, por UNA alita: 79 kcal y 0,78 g de sal. Pon las que te comas con el contador", trucos:["79 kcal y 0,78 g de sal POR ALITA. Con el contador del menú pones las que sean.","Las cuentas que importan: 3 alitas son 2,3 g de sal (el 58% de tu tope del día) y 6 alitas son 4,7 g, o sea TODO tu día de sal en un solo plato.","Con 2 g de sal por 100 g son lo más salado de la carta de Burger King, ocho veces más saladas que los aros de cebolla.","8,3 g de proteína por alita, eso sí. La carne está bien; el problema es el rebozado y la salsa.","Dato oficial de Burger King España (presentaciones de 3 y de 6, que cuadran entre sí)."] },
  { id:"pj_alitas", n:"Alitas de pollo de Papa John's", rev:2, cat:"Restaurante y bar", u:"g", racion:150, sal:1.37, k:210, p:22.9, g:12.6, h:0.8, compra:"restaurante", trucos:["315 kcal y 2,06 g de sal la ración estimada. 34 g de proteína.","Para comparar: las de Burger King son 0,78 g de sal POR ALITA, o sea 2,3 g sólo tres. Las dos cadenas están en el mismo sitio: muy saladas."] },
  { id:"bk_aros_cebolla", n:"Aros de cebolla de Burger King (unidad 11,8 g)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:11.8, racion:5, sal:0.51, k:241, p:3.9, g:11.6, h:30.3, compra:"restaurante", nota:"Dato oficial de Burger King España. Cinco aros son 0,3 g de sal: lo menos salado de la carta", trucos:["142 kcal y 0,30 g de sal. Es lo MENOS salado de la carta de Burger King, y por mucho.","La de 13 aros son 370 kcal y 0,8 g de sal.","Si acompañas el Whopper, los aros suman poca sal. Las patatas Supreme de esa misma carta llevan 2 g: el triple que las normales."] },
  { id:"pj_aros_cebolla", n:"Aros de cebolla de Papa John's", rev:2, cat:"Restaurante y bar", u:"g", sal:0.78, k:243, p:3.9, g:12, h:29, compra:"restaurante" },
  { id:"tapa_calamares", n:"Calamares a la romana (de bar)", rev:2, cat:"Restaurante y bar", u:"g", racion:62, sal:1.34, k:281, p:6.2, g:21, h:17.3, compra:"bar", nota:"Estimado, no de etiqueta. Aquí la sal NO la pone el cocinero: el 82% viene en el rebozado industrial. Rango de la ración: 2,8 a 4,3 g", trucos:["174 kcal y 0,83 g de sal tu cuarto. La ración entera, 703 kcal y unos 3,3 g de sal.","CIFRA ESTIMADA, pero de las más firmes de las cinco: el 82% de la sal viene del rebozado industrial, que sí tiene etiqueta (1,25 g/100 g).","Aquí quitar el salero no sirve de nada: la sal ya viene puesta de fábrica."] },
  { id:"mcd_cheeseburger", n:"Cheeseburger de McDonald's (unidad 120 g)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:120, racion:1, sal:1.33, k:255, p:13.3, g:10.8, h:25, compra:"restaurante", nota:"Dato OFICIAL de McDonald's España. El peso sale de cruzar sus dos columnas: 306 kcal la ración entre 254 kcal por 100 g = 120 g", trucos:["306 kcal y 1,6 g de sal. Es la hamburguesa más pequeña de la carta y se nota: la mitad de calorías que un Cuarto de Libra (547).","En sal sale mejor parada pero no tanto: 1,6 g frente a 2,6. Sigue siendo el 40% de tu tope del día.","16 g de proteína por 306 kcal: de las hamburguesas de restaurante, la que mejor relación tiene.","Si el capricho es McDonald's y el día va cargado de sal, dos cheeseburgers (3,2 g) NO son mejor que un Cuarto de Libra (2,6 g). Una sí.","Cifra oficial de McDonald's España."] },
  { id:"pj_chococookie", n:"ChocoCookie de Papa John's", rev:2, cat:"Restaurante y bar", u:"g", racion:100, sal:0.84, k:451, p:6.8, g:21.3, h:57.9, compra:"restaurante", trucos:["451 kcal y 0,84 g de sal por 100 g, con 34 g de azúcar. Es el postre más caro en calorías de las cadenas que llevas."] },
  { id:"mcd_cono_helado", n:"Cono de helado de McDonald's (una ración)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:100, racion:1, sal:0.1, k:157, p:3.8, g:3.3, h:28, compra:"restaurante", nota:"Dato OFICIAL de McDonald's España, de su propia ficha. La unidad es la ración entera", trucos:["157 kcal y 0,1 g de sal. De los caprichos de restaurante es, con diferencia, el que menos daño hace: la mitad de calorías que las patatas medianas y veinticinco veces menos sal que el wrap.","20 g de azúcar, que es casi todo lo que aporta. Pero con 3,8 g de proteína y 3,3 de grasa, para ser un postre de restaurante está bien.","Si el capricho es McDonald's y el día va justo de sal, este es el que se puede permitir casi siempre.","Cifra oficial de McDonald's España, de su propia ficha de producto."] },
  { id:"tapa_croqueta", n:"Croqueta de jamón de bar (unidad 33 g)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:33, racion:1, sal:1.02, k:264, p:7.2, g:19.8, h:15.3, compra:"bar", nota:"Estimado. Por croqueta: 87 kcal y 0,34 g de sal. Cuadra con lo que midió AESAN en croquetas en España (1,3 g/100 g)", trucos:["87 kcal y 0,34 g de sal POR CROQUETA. Seis son 522 kcal y 2 g de sal.","CIFRA ESTIMADA, pero es la mejor anclada de las tapas: cuadra con lo que midió AESAN en croquetas en España (1,3 g de sal por 100 g).","Sorpresa: de las cinco tapas de bar, las croquetas fritas son LAS QUE MENOS SAL traen. Parecen lo peor y no lo son."] },
  { id:"mcd_quarter", n:"Cuarto de Libra con queso de McDonald's (una ración)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:100, racion:1, sal:2.6, k:547, p:33, g:29, h:38, compra:"restaurante", nota:"Dato OFICIAL de McDonald's España, de su propia ficha. La unidad es la ración entera", trucos:["547 kcal y 2,6 g de sal. Exactamente la misma sal que un Whopper, y cien calorías menos.","2,6 g son el 65% de tu tope del día en una sola hamburguesa. Si la tomas, el resto del día va sin pan Ortiz, sin queso y sin aceitunas.","33 g de proteína, que es lo mejor que tiene: más que un filete de pollo.","Cifra oficial de McDonald's España."] },
  { id:"mcd_mcflurry_kitkat", n:"McFlurry KitKat de McDonald's (una ración)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:100, racion:1, sal:0.4, k:419, p:7, g:11, h:72, compra:"restaurante", nota:"Dato OFICIAL de McDonald's España. 54 g de azúcar en un vaso: el producto con más azúcar de todo el catálogo", trucos:["419 kcal y 0,4 g de sal. Casi el triple de calorías que el cono de helado (157) por el mismo tipo de capricho.","54 g de AZÚCAR, que es el dato de verdad: el producto con más azúcar de todo tu catálogo. Son unos trece terrones en un vaso, y la recomendación de la OMS para todo el día son 25 g.","Si lo que apetece es el helado de McDonald's, el cono te da la misma cosa por 157 kcal y 20 g de azúcar. La diferencia entre los dos es de las que se notan al mes.","Cifra oficial de McDonald's España."] },
  { id:"mcd_wrap_cbo", n:"McWrap CBO de McDonald's (unidad 243 g)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:243, racion:1, sal:1.11, k:262, p:10.7, g:14, h:23.5, compra:"restaurante", nota:"Dato de McDonald's FRANCIA: España no publica el del CBO y el Snack Wrap americano es otro producto, mucho más pequeño. Dos fichas francesas independientes coinciden en 2,7-3,0 g de sal por wrap", trucos:["639 kcal y 2,7 g de sal. Es el producto con MÁS CALORÍAS de todo tu catálogo de caprichos, por encima del Whopper (643 va casi empatado) y muy por encima del Cuarto de Libra (547).","2,7 g de sal son dos tercios de tu tope del día. En eso empata con el Whopper y supera al Cuarto de Libra.","No te fíes de la palabra «wrap»: suena a ligero y es lo contrario. Son 243 g y 34 g de grasa.","CIFRA FRANCESA, no española: McDonald's España no publica la del CBO. Dos fichas francesas distintas dan 2,7 y 3,0 g de sal, así que tómalo como «alrededor de 640 kcal y cerca de 3 g de sal»."] },
  { id:"tapa_oreja", n:"Oreja de cerdo a la plancha (de bar)", rev:2, cat:"Restaurante y bar", u:"g", racion:50, sal:1.42, k:210, p:16, g:16, h:0.2, compra:"bar", nota:"Estimado, no de etiqueta. Rango de sal en la ración entera: 1,8 a 4,3 g. La oreja de bar suele venir ya adobada, con más sal de partida", trucos:["105 kcal y 0,71 g de sal tu cuarto. La ración entera son 420 kcal y unos 2,8 g de sal.","CIFRA ESTIMADA, no de etiqueta: la oreja de bar no lleva ninguna. El rango real de la ración va de 1,8 a 4,3 g de sal según cómo venga adobada.","Casi toda la sal la pone el bar, no el alimento: la oreja cocida tiene 0,42 g por 100 g y el plato acaba en 1,4."] },
  { id:"pj_mozza_sticks", n:"Palitos de mozzarella de Papa John's", rev:2, cat:"Restaurante y bar", u:"g", racion:120, sal:1.8, k:282, p:12, g:13, h:28, compra:"restaurante", nota:"1,8 g de sal por 100 g: el entrante más salado de su carta", trucos:["338 kcal y 2,16 g de sal la ración estimada: más de la mitad de tu día.","1,8 g de sal por 100 g, el entrante más salado de su carta.","El pan de ajo con mozzarella lleva el mismo queso y un tercio de la sal."] },
  { id:"pj_pan_ajo", n:"Pan de ajo con mozzarella de Papa John's", rev:2, cat:"Restaurante y bar", u:"g", racion:150, sal:0.47, k:232, p:8.9, g:7.8, h:34.4, compra:"restaurante", nota:"Dato oficial de Papa John's España. El entrante MENOS salado de su carta, casi cuatro veces menos que los palitos de mozzarella", trucos:["348 kcal y 0,71 g de sal la ración estimada.","Es el entrante MENOS salado de su carta: 0,47 g por 100 g, casi cuatro veces menos que los palitos de mozzarella (1,80). Contraintuitivo y es el dato oficial.","Si vas a pedir un entrante en Papa John's, este es el que menos te cuesta en sal."] },
  { id:"pj_patatas", n:"Papas (patatas) de Papa John's", rev:2, cat:"Restaurante y bar", u:"g", racion:150, sal:1.2, k:142, p:2, g:5.5, h:20, compra:"restaurante", nota:"1,2 g de sal por 100 g: de los más salados de su carta pese a parecer lo más inocente", trucos:["213 kcal y 1,8 g de sal la ración estimada. Ojo: 1,2 g por 100 g es de lo más salado de su carta, más que sus propios aros de cebolla."] },
  { id:"tapa_bravas", n:"Patatas bravas (de bar)", rev:2, cat:"Restaurante y bar", u:"g", racion:75, sal:1.02, k:192, p:2.2, g:12.6, h:18.6, compra:"bar", nota:"Estimado, no de etiqueta. Casi toda la sal está en la SALSA: las comerciales van de 1,1 a 4,9 g/100 g. Rango de la ración: 1,5 a 6 g de sal", trucos:["144 kcal y 0,77 g de sal tu cuarto. La ración entera, 577 kcal y unos 3 g de sal.","CIFRA ESTIMADA. Y es la de rango más ancho de todas: de 1,5 a 6 g de sal en la ración, según el bar.","El culpable es la SALSA, no la patata: las salsas bravas comerciales van de 1,1 a 4,9 g de sal por 100 g. Pedir la salsa aparte y mojar poco es lo único que mueve de verdad este número."] },
  { id:"pj_pechuguitas", n:"Pechuguitas de pollo de Papa John's", rev:2, cat:"Restaurante y bar", u:"g", sal:1.39, k:206, p:16.9, g:7.4, h:17.2, compra:"restaurante" },
  { id:"pizza_bbq_pollo", n:"Pizza mediana barbacoa con pollo (restaurante, 525 g)", rev:2, cat:"Restaurante y bar", u:"g", racion:262, sal:1, k:197, p:9.4, g:5.2, h:26.7, compra:"restaurante", nota:"Domino's Portugal, mediana de 525 g. La menos salada y la menos calórica de las tres", trucos:["516 kcal y 2,6 g de sal la media pizza.","Es la menos mala de las tres en las dos cuentas: menos grasa (5,2 g/100 g frente a 10,9 de la carbonara) y menos sal que la de pepperoni.","A cambio lleva más azúcar, de la salsa barbacoa: 6,5 g por 100 g.","APROXIMACIÓN de la tabla oficial de Domino's Portugal, no dato español."] },
  { id:"pizza_carbonara", n:"Pizza mediana carbonara (restaurante, 525 g)", rev:2, cat:"Restaurante y bar", u:"g", racion:262, sal:0.9, k:228, p:10.2, g:10.9, h:21.3, compra:"restaurante", nota:"Domino's Portugal, mediana de 525 g", trucos:["597 kcal y 2,4 g de sal la media pizza. La menos salada de las tres, pero la que más calorías tiene.","APROXIMACIÓN de la tabla oficial de Domino's Portugal, no dato español."] },
  { id:"pizza_pepperoni", n:"Pizza mediana de pepperoni (restaurante, 465 g)", rev:2, cat:"Restaurante y bar", u:"g", racion:232, sal:1.3, k:233, p:10.9, g:9.8, h:24.4, compra:"restaurante", nota:"Domino's Portugal, mediana de 465 g y 8 porciones. Media pizza son 542 kcal y 3 g de sal", trucos:["541 kcal y 3,0 g de sal la media pizza. Los 3 g son el 75% de tu tope del día.","Por porción: 135 kcal y 0,75 g de sal. Con dos porciones ya vas por 1,5 g.","APROXIMACIÓN, no dato español: sale de la tabla oficial de Domino's PORTUGAL, porque la española no se puede consultar. El mismo producto varía bastante entre países.","De las tres pizzas de restaurante que tienes, esta es la más salada."] },
  { id:"tapa_sepia", n:"Sepia a la plancha (de bar)", rev:2, cat:"Restaurante y bar", u:"g", racion:47, sal:2.28, k:160, p:21.4, g:7.2, h:1.1, compra:"bar", nota:"Estimado. LA SEPIA YA TRAE 0,93 g de sal por 100 g ANTES de salarla: es el único de estos platos salado de origen. Rango de la ración: 3,3 a 5,8 g", trucos:["75 kcal y 1,07 g de sal tu cuarto. La ración entera, 304 kcal y unos 4,3 g de sal.","ES LA TAPA MÁS SALADA DE LAS CINCO, y parece la más sana: poca grasa, 40 g de proteína la ración. Justo por eso conviene saberlo.","La mitad de esa sal no la pone el bar: LA SEPIA YA TRAE 0,93 g por 100 g de origen, como todos los moluscos de mar. Pedir que no la salen ayuda, pero no la deja limpia.","CIFRA ESTIMADA. Rango de la ración: de 3,3 a 5,8 g de sal."] },
  { id:"mcd_topfries_bacon", n:"Top Fries Bacon & Cheese de McDonald's, individuales (una ración)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:100, racion:1, sal:1.5, k:423, p:12, g:22, h:42, compra:"restaurante", nota:"Dato OFICIAL de McDonald's España. 1,5 g de sal: más del doble que unas patatas normales", trucos:["423 kcal y 1,5 g de sal. Es lo más salado que has metido de McDonald's: el 37% de tu tope del día en un acompañamiento.","Para comparar: las patatas medianas normales son 320 kcal y 0,66 g de sal. El bacon y el queso te cuestan 100 kcal más y MÁS DEL DOBLE de sal.","Tanta sal como 30 g de jamón ibérico, que es el producto más salado de tu catálogo.","12 g de proteína y 4,1 g de fibra, eso sí. No es solo grasa.","Cifra oficial de McDonald's España."] },
  { id:"bk_whopper", n:"Whopper de Burger King (unidad 289 g)", rev:2, cat:"Restaurante y bar", u:"ud", pesoUd:289, racion:1, sal:0.9, k:222, p:10.5, g:12.5, h:16.9, compra:"restaurante", nota:"Dato oficial de Burger King España. Uno solo son 643 kcal y 2,6 g de sal: casi dos tercios de tu día de sal", trucos:["643 kcal y 2,6 g de sal. Las kcal son un tercio de tu día; la sal, casi dos tercios de tu tope de 4 g.","30 g de proteína, que no está mal. El problema es la sal, no la hamburguesa.","Dato oficial de Burger King España, no estimado."] }
];
